- repo/pom.xml
- repo/src/main/java/io/hyperfoil/tools/repo/api/RunService.java
- repo/src/main/java/io/hyperfoil/tools/repo/api/SchemaService.java
- repo/src/main/java/io/hyperfoil/tools/repo/entity/converter/JsonSerializer.java
- repo/src/main/java/io/hyperfoil/tools/repo/entity/converter/JsonUserType.java
- repo/webapp/src/components/Editor/Editor.js
@willr3 I have removed the jitpack dependency; could you release yaup 0.5 and **then** integrate this?
> Use JSON validation from yaup

- README.md
Added to the readme with a little more explanation of the purpose of the project.
Added tooling set up instructions.
> Added to readme file with description and set up instructions.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
> Avoid writing to response that's aleady committed.

- README.md
- podman-compose.yml
This PR fixes #117.
Added hostnet mode to pod definition.
Added README notes for using recent podman-compose version v1.x.
> Update podman compose file to be compatible with v1.x podman-compose tool.

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/entity/json/DataSet.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/entity/json/OwnedEntityBase.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/entity/json/ProtectedBaseEntity.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/entity/json/Run.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
> Added DataSet entity and configuration to changeLog.

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/entity/json/DataSet.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
This PR resolves most changes in #138 . There is an issue with the propagation of the role to the listener parameters.
> Added functions and event listener to create Run-DataSet association.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
Show in notification groups to identify results
> Add group to missing variable notification

- horreum-api/pom.xml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/RunService.java
To avoid misunderstandings in token I suggest adding a description to the swagger
> Add swagger alert for token param

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection/RelativeDifferenceChangeDetectionModel.java
Showing % in difference between previous and current mean
> View how big the ratio was detected

- .github/workflows/main.yml
Allow manual running of ci actions
> Allow manual execution of CI workflow. Display maven version info in CI

- horreum-backend/src/main/resources/horreum.sh
- horreum-client/src/test/java/io/hyperfoil/tools/HorreumTestBase.java
- horreum-client/src/test/resources/env.properties
- horreum-client/src/test/resources/testcontainers/horreum-compose.yml
Add feature to provide additional jvm options to Horreum container. Useful for debugging.
> Add jvm options flag for starting jvm in the container.

- example-data.sql
- webapp/src/domain/runs/Run.tsx
- webapp/src/domain/tests/RecalculateDatasetsModal.tsx
- webapp/src/domain/tests/Transformers.tsx
This PR changes text from recalculate to re-transform. To make coming changes in the docs align with the application.
> Change button text and dialogues to use re-transform text.

- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
Signing access tokens at static init time was causing this exception running tests in intellij: SRJWT05021: Please set 'smallrye.jwt.sign.key.location' or 'smallrye.jwt.sign.key' property
> Fix unit tests in intellij

- README.md
Add java 11 resource in readme.md
> Add java 11 resource in readme.md

- README.md
docs: update Getting Started to more clear
> docs: update Getting Started to more clear

- README.md
> docs: update access section

- README.md
> docs: add contributor list

- README.md
docs: update local development
> docs: update local development

- pom.xml
update: quinoa version 1.2.4 to 1.2.5
> update: quinoa version 1.2.4 to 1.2.5

- pom.xml
> add: shivam as developer

- pom.xml
- add cleanNode cache profile
close: #433
> add remove node cache

- .github/workflows/welcome.yml
- add welcome and issue for contributors
- close; #439
> add welcome workflow

- pom.xml
upgarade: netty from 1.1.87 to 4.1.90
> [#443] upgarade: netty from 1.1.87.final to 4.1.90.final

- pom.xml
> update: jackson version

- pom.xml
> Bump netty 4.1.91.final

- pom.xml
Bump quarkus 2.16.5 to 2.16.6.final
> Bump quarkus 2.16.5 to 2.16.6.final

- pom.xml
update: quinoa 1.2.9 from 1.2.8
> update: quinoa 1.2.9 from 1.2.8

- .github/workflows/audit.yml
- .github/workflows/main.yml
- .github/workflows/quay.yml
- .github/workflows/stable.yml
update: main.yml
update:audit.yml
update: quay.yml
update: stable.yml
> fix: deprecated version of github actions

- webapp/src/App.tsx
change: Text style of navbar items
> change: Text style of navbar items

- webapp/src/domain/tests/AllTests.tsx
AllTests.tsx: Sort by name
Fixes issue: #389
> [#389] AllTests.tsx: Sort by name

- .github/workflows/welcome.yml
> Update: welcome workflow

- .github/workflows/main.yml
Some file path-ignore in Java CI with Maven
> Some file path-ignore in Java CI with Maven

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-model/src/main/java/io/hyperfoil/tools/horreum/api/SchemaService.java
- webapp/src/domain/schemas/AllSchema.tsx
- webapp/src/domain/schemas/actions.ts
> Add: AllSchema.tsx Pagination

- infra/create-db.sh
- infra/docker-compose.yml
- infra/podman-compose.sh
Fixes networking issues with latest version of podman/podman-compose
> Enable Infra on new versions of podman

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
This PR fixes issue #539 
And null reference checking. Add a warn log message if too many null references are detected to proceed with the new Datapoint.
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
> Add null reference checking.

- webapp/src/domain/reports/TableReportConfigPage.tsx
> destructure TableReportConfigPage.tsx props

- pom.xml
> Bump jackson

- horreum-backend/src/main/resources/application.properties
> quinoa install node 18.16.1

- webapp/src/domain/alerting/PanelChart.tsx
- webapp/src/domain/alerting/RecalculateModal.tsx
Destructure component of alerting
>  Destructure component of alerting

- doc/Windows.md
add example configuration for windows in docs
> add example configuration for windows

- horreum-backend/pom.xml
> IllegalState Could not initialize plugin  

- webapp/src/components/FolderSelect.tsx
- webapp/src/components/FunctionFormItem.tsx
- webapp/src/components/HelpPopover.tsx
- webapp/src/components/LabelsSelect.tsx
- webapp/src/components/NotificationMethodSelect.tsx
- webapp/src/components/NumberBound.tsx
- webapp/src/components/OwnerAccess.tsx
> destructure component

- webapp/src/components/EnumSelect.tsx
- webapp/src/components/ImportButton.tsx
- webapp/src/components/LabelsSelect.tsx
- webapp/src/components/NotificationMethodSelect.tsx
- webapp/src/components/OptionalFunction.tsx
- webapp/src/components/SplitForm.tsx
- webapp/src/components/Table.tsx
- webapp/src/components/ViewSelect.tsx
- webapp/src/domain/schemas/FindUsagesModal.tsx
- webapp/src/domain/schemas/Labels.tsx
- ### [x] All new and existing tests passed.
> common refractor

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
> Remove isDebugEnabled wrapper

- horreum-backend/pom.xml
fixes #668 
[x] - Add maven dependency
> Add jsr305 dependency.

- webapp/src/404.tsx
- webapp/src/App.tsx
- webapp/src/index.css
> created 404 page, fixes #715

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
> fixes #726, fixes testImportExport to not be affected by lingering data

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
> fixes #726 for real

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
> fixes #733

- horreum-backend/src/main/resources/application.properties
See- https://github.com/quarkiverse/quarkus-quinoa/pull/558#discussion_r1373076035
> Config: package install automatically detect by quinoa

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
> fixes #800

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/RunDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
> fixes #811

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/LabelDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/LabelValueDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/LabelMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
> fixes #831

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
Tested it locally against the quarkus-quickstart schema. Removed a label, was able to save and did not see any stacktraces.
> fixes #842

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/main/resources/db/changeLog.xml
> Remove triggers from SchemaService.addOrUpdateLabel, reimplement recalc_dataset_view

- horreum-web/src/components/AccessIconOnly.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/runs/TestRuns.tsx
- horreum-web/src/domain/schemas/AllSchema.tsx
- horreum-web/src/domain/tests/AllTests.tsx
I followed our previous discusssion https://github.com/Hyperfoil/Horreum/pull/526#issue-1706915457
> Combine: owner and access columns, fixes #404 #405 #428 #430

- infra/horreum-infra-common/pom.xml
> dowgrade min JDK version for horreum-infra-common

- horreum-web/src/domain/runs/TestDatasets.tsx
> Correctly render dataset filters - Fixes #908

- horreum-backend/src/main/resources/application.properties
> correct config for keycloak admin client in dev mode : Fixes #911

- horreum-web/src/App.tsx
> Add hover effect on nav elements, fixes #826

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ReportComponentMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
> Do not filter report config if report is not peristed:  Fixes #877

- .github/workflows/main.yml
> Run GH workflows against all branches

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
> Null ID for schema if id less than : Fixes #924

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExperimentComparison.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ExperimentComparisonDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/tests/Experiments.tsx
> Correct experiment datatypes in UI. Retrun experiment results in prod mode

- pom.xml
> Automatically copy generated openapi.yaml to docs/site - Fixes #932

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
- pom.xml
> Bump postgres to version 16

- docs/site/content/en/openapi/openapi.yaml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/resources/application.properties
> Lookup testID with DatasetID by schema: Fixes #917

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
> Check if dev services backup directory exists and is not empty

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
> Correctly query for looking up watches: Fixes #950

- docs/DEVELOPMENT.md
> mention semver goal in DEVELOPMENT.md

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Starting Horreum in quarkus dev mode fails to boot correctly for some obscure reason.
Adds conditions to check directory permissions when starting the Postgres resource.
> Add permissions check on PG dump directory and helpful error message.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
> Lookup fingerprints by hash in database : Fixes #962

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- pom.xml
Support Docker Desktop for building native executables with quarkus 3.6.0
The @Blocking annotations validation are new in Quarkus 3.6.0
> Support Docker Desktop for building native executables with quarkus 3.6.0

- horreum-backend/src/main/resources/application.properties
Upgrade: latest LTS node v20.10.0 and npm 10.2.3
> Upgrade: latest LTS node v20.10.0 and npm 10.2.3

- .github/workflows/main.yml
> CI: depreciated github action

- pom.xml
> Bump quarkus

- pom.xml
it uses latest node version
nextjs support
> Use latest version of quinoa 2.3.0

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
This reverts commit 34d62dcdd67c0f0a2ffc39ed5db6dfbb799c5500.
Fixes #972
> Revert "Add permissions check on PG dump directory and helpful error message."

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
> Correctly handle JSON types in DB query in SchemaServiceImpl.findUsages()

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
> Correctly handle JSON types in DB query in SchemaServiceImpl.findUsages() 

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ValidationError.java
> NPE: Retransform Datasets

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-web/src/domain/reports/TableReportView.tsx
> update run_schemas table, prevent js bug from crashing UI, correctly cast metadata

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-web/src/domain/reports/TableReportView.tsx
> update run_schemas table, prevent js bug from crashing UI, correctly cast metadata.

- pom.xml
See feature-https://github.com/apache/maven-compiler-plugin/releases/tag/maven-compiler-plugin-3.12.0
> Chore: maven compiler 3.12.1

- pom.xml
Smart bypass of the dev server SPA
> Bump quinoa.version - 2.3.1

- .github/dependabot.yml
> Re-enable dependabot dependency checking

- pom.xml
> remove explicit dependency on jackson-datatype-jsr310: Fixes #1025

- horreum-backend/pom.xml
- horreum-client/pom.xml
- horreum-integration-tests/pom.xml
- pom.xml
> Extract plugin versions to maven properties

- horreum-backend/pom.xml
- pom.xml
> Unify json-schema-validator dependency version : 

- infra/horreum-dev-services/pom.xml
> Resolve surefire-plugin.version from parent pom

- horreum-web/src/domain/tests/RecalculateDatasetsModal.tsx
> Do not fetch Test details for RecalculateDatasetsModal unless modal is open

- horreum-integration-tests/pom.xml
- pom.xml
> Unify quarkus & plugin versions

- horreum-backend/pom.xml
> remove jandex-maven-plugin

- horreum-web/package-lock.json
- horreum-web/package.json
- pom.xml
> Bump keycloak from 22.0.4 to 23.0.3

- docs/site/content/en/docs/Deployment/bare-metal.md
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-integration-tests/src/main/resources/application.properties
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/SelfSignedCert.java
> Remove db encryption with pgcrypto

- horreum-api/pom.xml
- horreum-client/pom.xml
- horreum-integration-tests/pom.xml
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
- pom.xml
> Release Integration Test jars and push to sonatype staging : Fixes #897

- pom.xml
> Add missing pom property

- horreum-integration-tests/src/main/java/io/hyperfoil/tools/horreum/it/HorreumIntegrationTest.java
> Add empty class to generate javadoc

- pom.xml
> Revert releasing to staging - need to push file signatures

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/DatasetLog.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/TransformationLog.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ActionLog.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/PersistentLog.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/ReportComponent.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/ReportLog.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/TableReport.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/TableReportConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
> added more @Schema definitions to comply with the openapi-python-client, fixes #930

- docs/site/content/en/openapi/openapi.yaml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> change sql statements to text blocks

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
> Improve error message when creation of a new user fails

- horreum-backend/src/main/resources/application.properties
> Upgrade nodejs and npm

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
> Backport of #1075

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
> Create composite Manager role for new team. Fixes #970

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
> Backport of #1104

- pom.xml
> Backport of #1102

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1010

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1081

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1060

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1115

- horreum-web/src/domain/runs/DatasetData.tsx
fixes #1077 
[x] - Changed button
> Configured button to be disabled when Experiments don't exist.

- horreum-web/src/domain/tests/Experiments.tsx
fixes #1100 
[x] - add field name
> Added field name for Variable.

- horreum-web/src/domain/tests/Experiments.tsx
> Backport of #1113

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1061

- horreum-web/src/api.tsx
fixes issue #839 
[x] - Changed existing error condition message
> Added suggestion to progress beyond current missing Run error.

- horreum-web/src/api.tsx
> Backport of #1119

- pom.xml
> Backport of #1134

- pom.xml
> Backport of #1135

- horreum-web/package-lock.json
- horreum-web/package.json
> Backport of #1136

- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/404.tsx
- horreum-web/src/App.tsx
- horreum-web/src/components/IndirectLink.tsx
- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/reports/TableReportView.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
- horreum-web/src/index.tsx
Migration react-router-dom 5 to v6 
fixes: #723
> Migration react-router-dom 5 to 6

- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/404.tsx
- horreum-web/src/App.tsx
- horreum-web/src/components/IndirectLink.tsx
- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/reports/TableReportView.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
- horreum-web/src/index.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1004
Migration react-router-dom 5 to v6 
fixes: #723
> [0.11.x] Migration react-router-dom 5 to 6

- .github/workflows/backport.yml
> Add backport GH action to auto backport PRs to stable branch

- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/404.tsx
- horreum-web/src/App.tsx
- horreum-web/src/components/IndirectLink.tsx
- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/reports/TableReportView.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
- horreum-web/src/index.tsx
> Bump packagelock

- horreum-web/package-lock.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1148
> [0.11.x] Bump packagelock

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
This reverts commit 980102960d700cb126b543a0ac1d8d41e03415e1.
> Revert "Compare fingerprints by hash"

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1150
This reverts commit 3d5bc4d9a6e923a41158f08b19dc8a7fa8b2e174.
> [0.11.x] Revert "Compare fingerprints by hash"

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
- horreum-web/index.html
- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/index.tsx
- horreum-web/src/setupProxy.js
- horreum-web/tsconfig.json
- horreum-web/vite-env.d.ts
- horreum-web/vite.config.ts
CRA (create-react-app) is no longer maintained. Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects
closes: #995
> Migration CRA to VITE

- horreum-web/package-lock.json
> [0.11.x] Bump package-lock.json

- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/404.tsx
- horreum-web/src/App.tsx
- horreum-web/src/components/IndirectLink.tsx
- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/reports/TableReportView.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
- horreum-web/src/index.tsx
This reverts commit 8f0d1a280e705f4ee2ee20d1de44dc10f0300e8b.
> Reapply "Migration react-router-dom 5 to 6, fixes #723"

- horreum-web/src/domain/reports/TableReportConfigPage.tsx
- horreum-web/src/domain/reports/TableReportPage.tsx
- horreum-web/src/domain/runs/Run.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/schemas/Schema.tsx
- horreum-web/src/domain/tests/Test.tsx
> Migrate useParams from react-router react-router-dom: Fixes #

- horreum-web/src/domain/reports/TableReportConfigPage.tsx
- horreum-web/src/domain/reports/TableReportPage.tsx
- horreum-web/src/domain/runs/Run.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/schemas/Schema.tsx
- horreum-web/src/domain/tests/Test.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1166
Fixes: #1167
> [0.11.x] Migrate useParams from react-router react-router-dom: Fixes #

- docs/RELEASE.md
> Dev Docs: backporting

- horreum-web/package-lock.json
- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1169
> [0.11.x] Use specific versions of node dependency

- horreum-web/vite.config.ts
> Set base path for vite builds: Fixes #1176

- horreum-web/package-lock.json
- horreum-web/src/domain/runs/RunList.tsx
> Migrate useParams from react-router react-router-dom for Runs: Fixes #1199

- horreum-web/vite.config.ts
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1201
Fixes #1176
> [0.11.x] Set base path for vite builds: Fixes #1176

- horreum-web/src/domain/runs/RunList.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1200
Fixes #1199
> [0.11.x] Migrate useParams from react-router react-router-dom for Runs: Fixes #1199

- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1193
> [0.11.x] Vite CJS Node API deprecated

- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/alerts.tsx
- horreum-web/src/api.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/keycloak.ts
- horreum-web/src/store.ts
> Remove 'history' from redux store.ts: Fixes #1232

- horreum-backend/pom.xml
> remove unnecessary dependencies: Fixes #1237

- horreum-backend/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1238
Fixes #1237
> [0.11.x] remove unnecessary dependencies: Fixes #1237

- horreum-web/package-lock.json
- horreum-web/package.json
> Fix conflicting npm dependencies and bump typescript 4 to 5

- horreum-web/package-lock.json
- horreum-web/src/alerts.tsx
- horreum-web/src/api.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/keycloak.ts
- horreum-web/src/store.ts
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1233
Fixes #1232
> [0.11.x] Remove 'history' from redux store.ts: Fixes #1232

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-web/src/Login.tsx
- horreum-web/src/api.tsx
- horreum-web/src/keycloak.ts
> Add endpoint to fetch the roles of an authenticated user: Fixes #1187

- .github/workflows/main.yml
- docs/RELEASE.md
> Run CI for stable branch with each push

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-web/src/Login.tsx
- horreum-web/src/api.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/keycloak.ts
> Add endpoint to fetch the roles of an authenticated user ; Fixes #1246

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-web/src/keycloak.ts
> Always fetch roles from backend :  Fixes #1255

- docs/site/content/en/openapi/openapi.yaml
- horreum-backend/src/main/resources/application.properties
- horreum-web/package-lock.json
- Downgrade npm to same version as CI
Fixes #1269
> Re-commit package-lock.json with the correct spacing. Fixes #1269

- horreum-backend/src/main/resources/application.properties
- horreum-web/package-lock.json
> [0.11.x] Re-commit package-lock.json with the correct spacing. Fixes #1269

- horreum-web/package-lock.json
- horreum-web/package.json
> Remove immutable dependency : Fixes #1272

- horreum-web/package-lock.json
- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1273
Fixes #1272
> [0.11.x] Remove immutable dependency : Fixes #1272

- horreum-web/src/App.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/domain/admin/Admin.tsx
> Display datastore config to managers in Admin tab: Fixes #1275

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/pom.xml
- horreum-web/src/api.tsx
- horreum-web/src/domain/runs/RunList.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/schemas/SchemaList.tsx
- horreum-web/src/domain/schemas/TestLabelModal.tsx
- horreum-web/src/domain/schemas/TryJsonPathModal.tsx
- horreum-web/src/domain/tests/AllTests.tsx
The upgrade causes the ordering of some argumets for the generated api which required some changes to tsx files
> upgrade smallrye-openapi to 3.9

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/BaseDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/Datastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/PostgresDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-web/package-lock.json
- horreum-web/src/App.tsx
- horreum-web/src/domain/admin/Datastores.tsx
- horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> Implement Basic Authentication for Elasticsearch datastore: Fixes #1295

- horreum-backend/src/main/resources/application.properties
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
- Propagate credentials from .env file 
- Remove the hard-coded IP address and replace with the defined network alias
> Fix devservices with DB backup

- horreum-backend/src/main/resources/application.properties
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1288
- Propagate credentials from .env file 
- Remove the hard-coded IP address and replace with the defined network alias
> [0.11.x] Fix devservices with DB backup

- horreum-web/src/App.tsx
- horreum-web/src/alerts.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/tests/General.tsx
> fixes #1310: remove console references

- horreum-web/src/domain/runs/DatasetComparison.tsx
fixes #744 
[x] - Render the component values in a table
> Implementation of using BarValuesChart to display View Component values.

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ProtectedTimeType.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Closes #1321
More API improvements related to #1092 for downstream tools to select only the desired data from Horreum
> fix #1321 added sorting & filtering, and start, stop

- horreum-web/src/App.tsx
- horreum-web/src/alerts.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/tests/General.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1311
Closes #1310
> [0.11.x] fixes #1310: remove console references

- horreum-web/src/domain/runs/RunImportModal.tsx
fixes #1341
[x] - Fixed order of parameters.
[x] - Changed misleading helper text
> Relocated owner. Corrected bogus HelperTextItem text.

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/pom.xml
- pom.xml
> Synchronize openapi.yaml with current api definition: Fixes #1351

- horreum-web/src/domain/runs/RunList.tsx
- horreum-web/src/domain/runs/components.tsx
fixes #957 
[x] - Clear any selection of rows when a row has been deleted
[ ] - Not correct; marked as **not** done-->
> Clear selected rows after Deletion of a row. fixes #957

- horreum-web/src/domain/runs/RunList.tsx
- horreum-web/src/domain/runs/components.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1342
fixes #957 
[x] - Clear any selection of rows when a row has been deleted
[ ] - Not correct; marked as **not** done-->
> [0.11.x] Clear selected rows after Deletion of a row. fixes #957

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
> Remove System.out.println, fixes #1356

- horreum-web/package-lock.json
- horreum-web/package.json
> remove ajv dependency: Fixes #1382

- horreum-web/package-lock.json
- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1383
Fixes #1378
> [0.11.x] remove ajv dependency: Fixes #1382

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UIService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UIServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/api.tsx
- horreum-web/src/domain/tests/Views.tsx
Reverts Hyperfoil/Horreum#1316
This changed the API, we need 0.11.x to be stable
> Revert "[0.11.x] closes #1312 with updated UIService api"

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ValidationError.java
- horreum-web/src/domain/runs/ValidationErrorTable.tsx
> Reintroduce deprecated schemaPath property in ValidationError: Fixes #1345

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/Team.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/TeamMembership.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatabaseUserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/resources/application.properties
> `UserService` that manages users in Horreum DB - Fixes #1260

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-web/src/api.tsx
> fix #1402 avoid default limit and page

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RolesAugmentor.java
> Security augmentor fixes #1258

- .github/workflows/backport.yml
Update backport workflow to 0.12.x branch
> Update backporting to 0.12.x branch

- horreum-web/package-lock.json
fixes #1421 and 
[x] - rebuild file
> Re-created package-lock.json

- horreum-web/package-lock.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1429
fixes #1421 and 
[x] - rebuild file
> [0.12.x] Re-created package-lock.json

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
> Remove @NaturalId annotation from UserInfo: Fixes #1418

- horreum-web/src/auth.tsx
> [UI] fix selection of authentication mechanism

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1422
Fixes: #1418
> [0.12.x] Remove @NaturalId annotation from UserInfo: Fixes #1418

- horreum-web/src/auth.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1431
fixes #1420
> [0.12.x] [UI] fix selection of authentication mechanism

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
> Load all keycloak users on migration

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1432
Fixes: #1441 1441
> [0.12.x] Load all keycloak users on migration

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1451
> [0.12.x] upgrade to Quarkus 3.8.1, fixes #1244

- pom.xml
Reverts Hyperfoil/Horreum#1454
Reverting due to https://github.com/Hyperfoil/Horreum/issues/1456
> Revert "Bump quarkus.version from 3.8.1 to 3.8.2"

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- pom.xml
Reverts Hyperfoil/Horreum#1451
reverting due to: https://github.com/Hyperfoil/Horreum/issues/1456
> Revert "upgrade to Quarkus 3.8.1, fixes #1244"

- .github/workflows/check.yml
- horreum-web/.prettierrc
fixes #1427 
[x] - Add a workflow that checks the format of package-lock
> Add a GH Action workflow to check package-lock.json file for the commit.

- .github/workflows/check.yml
- horreum-web/.prettierrc
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1428
fixes #1427 
[x] - Add a workflow that checks the format of package-lock
> [0.12.x] Add a GH Action workflow to check package-lock.json file for the commit.

- .gitignore
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Extractor.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ExtractorDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExtractorMapper.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/schemas/JsonExtractor.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- infra-legacy/example-data/acme_transformer.json
- infra-legacy/example-data/quarkus_sb_schema.json
Fixes https://github.com/Hyperfoil/Horreum/issues/907
Fixes the `Extractor` OpeAPI schema object:
* Changes field from `array` to `isarray` as this must match the PSQL `extractor` type
More details on the root cause are described [here](https://github.com/Hyperfoil/Horreum/issues/907#issuecomment-1984089188).
> Fix test label calculation with all match

- .gitignore
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Extractor.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ExtractorDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExtractorMapper.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/schemas/JsonExtractor.tsx
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
- infra-legacy/example-data/acme_transformer.json
- infra-legacy/example-data/quarkus_sb_schema.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1461
Fixes https://github.com/Hyperfoil/Horreum/issues/907
Fixes the `Extractor` OpeAPI schema object:
* Changes field from `array` to `isarray` as this must match the PSQL `extractor` type
More details on the root cause are described [here](https://github.com/Hyperfoil/Horreum/issues/907#issuecomment-1984089188).
> [0.12.x] Fix test label calculation with all match

- docs/site/content/en/docs/Concepts/core-concepts/index.md
- docs/site/content/en/docs/Tasks/configure-actions/index.md
Added details of webhook types and an event type.
fixes #1177 
[x] - Added links to existing Configure Actions page.
[X] - Added more terms on Core Concepts page.
[x] - Added events that can be created in Horreum
[x] - Types of Action
> Added links on existing Configure Actions documentation page.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
> fix #1484 remove final pattern check

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
> fix#1484 remove final pattern check

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
The dispatch of some operations (`vertx.executeBlocking(...)`) cause trouble when calling the `UserServiceImpl` directly, like for testing., because lack of request context. 
Took the opportunity to perform some refactoring as well.
> Remove vertx dispatch and tiddy up UserServiceImpl

- horreum-web/src/domain/runs/components.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1449
> Fix render exception in tooltip

- horreum-web/src/domain/runs/components.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1527
Fixes https://github.com/Hyperfoil/Horreum/issues/1449
> [0.12.x] Fix render exception in tooltip

- horreum-web/package-lock.json
- horreum-web/package.json
This reverts commit 079ef80b41feaab49b79933c04f59230e135ee03.
> Revert "Bump react-to-print from 2.14.15 to 2.15.1 in /horreum-web"

- docs/site/content/en/openapi/openapi.yaml
Running `mvn clean install -DskipTests -DskipITs` from `master` branch generates the diff in this pull request.
Looks like the openapi generation was partially missed from https://github.com/Hyperfoil/Horreum/pull/1534, worth to note that they are just descriptions and examples.
Simply update the openapi spec.
> Regenerate openapi

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
This dependency will be problematic for a Quarkus upgrade.
It looks to me that it can be safely removed.
> Remove hypersistence dependency

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
fixes #1124  #1379 
[x] - Replace entity associated with session
> Fix ChangeDetection additions.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/Team.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/TeamMembership.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
> equals and hashcode implementation for user entities

- .github/workflows/main.yml
Bump to actions/upload-artifact@v4
> Bump to actions/upload-artifact@v4

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
> Execute TEST_NEW actions with the test id

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
#1409 
[x] - Changed RBAC on methods to Admin
[X] - Updated existing testcases
[X] - Added new testcase
[ ] - Not correct; marked as **not** done-->
> Added RBAC to UserService searchUsers and info methods.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1585
fixes #1353
> [0.12.x] Execute TEST_NEW actions with the test id

- horreum-web/src/.prettierignore
> Ignore reformat files/folder 

- horreum-web/src/.prettierignore
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1489
> [0.12.x] Ignore reformat files/folder 

- .github/workflows/notify-clients.yaml
I initially set wrong branch on trigger condition as in Horreum we have `master` and not `main`
> Trigger notify-clients workflows on master branch push

- horreum-web/vite.config.ts
We are not using this from long time and it is done by quarkus so Removing this.
> Remove unused object from vite.config.ts

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
With this PR I am adding some more test cases for the `SchemaServiceImpl` service, moreover I am fixing issue https://github.com/Hyperfoil/Horreum/issues/1592.
Fixes https://github.com/Hyperfoil/Horreum/issues/1592
Improved test coverage of `SchemaServiceImpl` service as well as fixed `updateAccess` functionality.
> Improve SchemaServiceImpl testing

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1600
With this PR I am adding some more test cases for the `SchemaServiceImpl` service, moreover I am fixing issue https://github.com/Hyperfoil/Horreum/issues/1592.
Fixes https://github.com/Hyperfoil/Horreum/issues/1592
Improved test coverage of `SchemaServiceImpl` service as well as fixed `updateAccess` functionality.
> [0.12.x] Improve SchemaServiceImpl testing

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
> Fix javadoc linting error

- docs/RELEASE.md
> Update RELEASE.md - set CI to ture for release builds

- pom.xml
Reverts Hyperfoil/Horreum#1618
> Revert "Bump graalvm.version from 23.1.2 to 24.0.1"

- docs/site/content/en/docs/Reference/horreum-clients.md
Update the clients reference documentation based on the following api changes:
They are going to change how the `HorreumClient` is initialized
> Update clients reference

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/hibernate/JsonBinaryType.java
> remove cast to String for JSON datatypes - Fixes #1642

- .github/workflows/backport.yml
> Update backport.yml to target 0.13.x

- .github/workflows/backport.yml
> Update backport.yml to 0.13.x

- horreum-backend/src/main/docker/Dockerfile.jvm.base
> Fix base image for release

- .github/workflows/main.yml
> Change workflow to run against 0.13.x branch

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
With this PR I am proposing teh following improvements:
* Before:
* After:
> Setup unit testing bypassing REST

- horreum-backend/src/main/docker/Dockerfile.jvm.base
> Correct User ID in base image: Fixes #1669

- horreum-web/src/domain/reports/ListReportsModal.tsx
- horreum-web/src/domain/schemas/FindUsagesModal.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1679
Fix the reports navigation links which are now in the format of `test/{testId}/reports/....`
> Fix reports nav links

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/main/resources/META-INF/beans.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
> Validate test/schema import format: Fixes #1685

- .github/scripts/ci-prerequisites.sh
- .github/workflows/main.yml
> Clear CI disk space before running tests. Fixes #1712

- horreum-web/src/domain/tests/AllTests.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1688
Sanitize the `folder` before adding it as URL query param.
> Sanitize folder before adding it as url query param

- horreum-web/src/App.tsx
> Reinstate errorElement for main route. Fixes #1716

- .github/scripts/ci-prerequisites.sh
- .github/workflows/main.yml
> [0.13.x] Clear CI disk space before running tests. Fixes #1712

- horreum-web/src/404.tsx
Use Link instead using NavLink to navigate 404
> Use `Link` instead `NavLink` to navigate 404

- .github/workflows/backport.yml
Use machine account @rh-appservices-perf token for backporting purposes.
> Use RH_PERF_BOT_TOKEN for backporting

- infra/horreum-infra-common/src/main/resources/postgres.config.properties
> Enable pg_stat_statements in postgres for dev mode: Fixes #1747

- infra/horreum-infra-common/src/main/resources/postgres.config.properties
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1748
Fixes #1747
> [0.13.x] Enable pg_stat_statements in postgres for dev mode: Fixes #1747

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/VariableMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/resources/data/acme_new_variable_test.json
- horreum-backend/src/test/resources/data/acme_sb_schema.json
Added testcase to flush out defect when importing an existing Test with new definitions of Change Detection variables. Added fixes to add new variables.
fixes #1740 
[x] - Allow more situation when a Test fields are updated
> Import Test change detection variable fixes.

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/domain/runs/TestDatasets.tsx
> Add new test service api to return label values for filter: Fixes #1767

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/VariableMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/resources/data/acme_new_variable_test.json
- horreum-backend/src/test/resources/data/acme_sb_schema.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1744
Added testcase to flush out defect when importing an existing Test with new definitions of Change Detection variables. Added fixes to add new variables.
fixes #1740 
[x] - Allow more situation when a Test fields are updated
> [0.13.x] Import Test change detection variable fixes.

- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
> split slack channel tests

- .github/workflows/branch.yml
> fix notify-clients.yaml name

- .github/workflows/branch.yml
This reverts commit d3086b935e97cb223c94037b2c9bebad6dd64726.
> Revert "Do not push branches"

- .github/workflows/branch.yml
> Action to push branches to origin

- .github/workflows/branch.yml
> branch action: Checkout with perf bot token

- .github/workflows/branch.yml
- .github/workflows/main.yml
- .github/workflows/notify-clients.yaml
> branch action: correct workflow target branches

- .github/workflows/branch.yml
- docs/site/content/en/openapi/openapi.yaml
> Bump openapi to 0.15

- .github/workflows/backport.yml
- .github/workflows/branch.yml
> new branch: update backport workflow branch

- README.md
Followup https://github.com/Hyperfoil/Horreum/pull/1708
Fix the initial username in case of Horreum dev mode.
Change the default username of the initial account while running in dev mode from `user` to `horreum.bootstrap`.
> Update initial user username

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
This enables tracking usage of `RoleManager` in the logs, to debug problems and help identify performance issues.
> Add debug log to RoleManager

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1804
This enables tracking usage of `RoleManager` in the logs, to debug problems and help identify performance issues.
> [0.14] Add debug log to RoleManager

- .github/workflows/branch.yml
- .github/workflows/release.yml
> Automate release in github action

- .github/workflows/release.yml
> Update Relase github action name

- .github/workflows/release.yml
> Auto release - Fix env variable lookup

- .github/workflows/release.yml
> auto release - fix gpg key import

- .github/workflows/release.yml
> auto release- alternative gpg key import

- .github/workflows/release.yml
> auto release- set gpg tty

- horreum-web/src/components/LabelFilter/FilterDropDown.tsx
- horreum-web/src/components/LabelFilter/LabelFilter.tsx
- horreum-web/src/components/LabelFilter/LabelFilterOption.tsx
- horreum-web/src/components/ToolbarLabelFilter.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1797
This PR changes the filter dropdown to use the Patternfly `attribute-search` pattern
Fixes:  #1346
> [0.14] Change dataset filters to Patternfly Attribute Filter pattern: Fixes: #1346

- horreum-backend/pom.xml
#1853 
configure test jar
[x] - update POM config
> Configure maven-jar-plugin to create a test classes jar.

- horreum-backend/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1854
#1853 
configure test jar
[x] - update POM config
> [0.14] Configure maven-jar-plugin to create a test classes jar.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
> Fix user search on keycloak instances without machine role

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1887
Fixes #1868
> [0.14] Fix user search on keycloak instances without machine role

- .github/workflows/release.yml
> Auto-release: fix gpg keys and publishing

- .github/workflows/release.yml
> Auto-release: add bot account details

- .github/workflows/release.yml
> Auto-release: Add release token with correct permissions

- .github/workflows/release.yml
> Add github tokens

- .github/workflows/release.yml
> register ssh key

- .github/workflows/release.yml
> Re-use calculated versions in env variables

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/main/resources/db/changeLog.xml
> Improve label values

- horreum-api/pom.xml
- horreum-backend/pom.xml
- infra/horreum-dev-services/deployment/pom.xml
- infra/horreum-infra-common/pom.xml
Take reference- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9
> Address artifact warnings after quarkus 3.9 release

- horreum-web/src/domain/alerting/PanelChart.tsx
> Annotate changes charts with Dot if value is zero: Fixes #1938

- horreum-web/src/domain/alerting/PanelChart.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1939
Fixes #1938
> [0.14] Annotate changes charts with Dot if value is zero: Fixes #1938

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/resources/application.properties
> Fix keycloak deployment in dev profile

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/health/HorreumHealthCheck.java
- horreum-backend/src/main/resources/application.properties
Fixes https://github.com/Hyperfoil/Horreum/issues/1955
Setup default health check endpoint using `quarkus-smallrye-health`.
Example of `http://localhost:8080/q/health/` call:
```json
{
"status": "UP",
"checks": [
{
"name": "SmallRye Reactive Messaging - liveness check",
"status": "UP",
"data": {
"dataset-event-in": "[OK]",
"schema-sync-out": "[OK]",
"schema-sync-in": "[OK]",
"dataset-event-out": "[OK]",
"run-recalc-out": "[OK]",
"run-recalc-in": "[OK]"
}
},
{
"name": "Horreum is ready to accept requests",
"status": "UP"
},
{
"name": "SmallRye Reactive Messaging - readiness check",
"status": "UP",
"data": {
"dataset-event-in": "[OK]",
"schema-sync-in": "[OK]",
"run-recalc-in": "[OK]",
"schema-sync-out": "[OK]",
"dataset-event-out": "[OK]",
"run-recalc-out": "[OK]"
}
},
{
"name": "Database …
```
> Setup smallrye health checks

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-backend/src/test/resources/data/experiment-ds10.json
- horreum-backend/src/test/resources/data/experiment-ds11.json
- horreum-backend/src/test/resources/data/experiment-ds4.json
- horreum-backend/src/test/resources/data/experiment-ds5.json
- horreum-backend/src/test/resources/data/experiment-ds6.json
- horreum-backend/src/test/resources/data/experiment-ds7.json
- horreum-backend/src/test/resources/data/experiment-ds8.json
- horreum-backend/src/test/resources/data/experiment-ds9.json
Offload processing multiple runs from datastore to async queue
Fixes #1858
> Offload multi run upload processing to message queue: Fixes #1858

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/health/HorreumHealthCheck.java
PR https://github.com/Hyperfoil/Horreum/pull/1956 was created before merging the automated formatting, but it was not rebased before merging it.. thus resulting in jobs failure from that moment on
Fix formatting
> Fix formatting

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/health/HorreumHealthCheck.java
- horreum-backend/src/main/resources/application.properties
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1956
Fixes https://github.com/Hyperfoil/Horreum/issues/1955
Setup default health check endpoint using `quarkus-smallrye-health`.
Example of `http://localhost:8080/q/health/` call:
```json
{
"status": "UP",
"checks": [
{
"name": "SmallRye Reactive Messaging - liveness check",
"status": "UP",
"data": {
"dataset-event-in": "[OK]",
"schema-sync-out": "[OK]",
"schema-sync-in": "[OK]",
"dataset-event-out": "[OK]",
"run-recalc-out": "[OK]",
"run-recalc-in": "[OK]"
}
},
{
"name": "Horreum is ready to accept requests",
"status": "UP"
},
{
"name": "SmallRye Reactive Messaging - readiness check",
"status": "UP",
"data": {
"dataset-event-in": "[OK]",
"schema-sync-in": "[OK]",
"run-recalc-in": "[OK]",
"schema-sync-out": "[OK]", …
```
> [0.14] Setup smallrye health checks

- .github/workflows/branch.yml
> Fix branch workflow

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/ArtemisMQResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
- infra/horreum-infra-common/src/main/resources/broker.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1979
#1978
> [0.15] Add ArtemisMQ and Horreum containers.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1969
There have been reports of IO treads blocked while sending out email notifications. 
Since horreum uses the async email extension, the other possible cause is qute templating.
> [0.15] Use async qute templating for email notifications

- config/eclipse-formatting.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/CustomSequenceGenerator.java
> Fix javadoc and formatter

- config/eclipse-formatting.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/CustomSequenceGenerator.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2003
> [0.15] Fix javadoc and formatter

- horreum-integration-tests/pom.xml
> remove horreum-integration-tests artefacts from build: fixes #2012

- horreum-integration-tests/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2013
fixes #2012
> [0.15] remove horreum-integration-tests artefacts from build: fixes #2012

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/ArtemisMQResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2005
fixes #1978
> [0.15] Make key names consistent with prior resources.

- infra/horreum-infra-common/pom.xml
- pom.xml
> Publish dev services container images: Fixes #2022

- infra/horreum-infra-common/pom.xml
- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2023
Fixes #2022
> [0.15] Publish dev services container images: Fixes #2022

- horreum-api/pom.xml
- horreum-client/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2026
> [0.15] Fix target version to JDK11 for api and client

- infra/horreum-infra-common/pom.xml
> Fix target version to JDK11 for infra-commons

- infra/horreum-infra-common/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2029
> [0.15] Fix target version to JDK11 for infra-commons

- horreum-web/src/App.tsx
> Show administration menu for Team Managers: Fixes #2045

- horreum-web/src/App.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2046
Fixes #2045
> [0.15] Show administration menu for Team Managers: Fixes #2045

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
> Fix elastic credentials check: Fixes #2047

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2048
Fixes #2047
> [0.15] Fix elastic credentials check: Fixes #2047

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/Datastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/PostgresDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
> Remove ObjectMapper from Datastore interface

- horreum-backend/pom.xml
- horreum-integration-tests/pom.xml
- horreum-web/package-lock.json
- horreum-web/package.json
- infra/horreum-dev-services/runtime/pom.xml
- infra/horreum-infra-common/pom.xml
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2025
Keycloak version was incompatible with services running SSO
Fixes: #2061
> [0.15] Downgrade Keycloak to 23.0.7

- .github/workflows/main.yml
- horreum-backend/src/main/docker/Dockerfile.jvm.base
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2080
Fixes https://github.com/Hyperfoil/Horreum/issues/2079
> [0.15] Fix python and hunter version

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/chore.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Automatically add some issue labels

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
> Fix JSON deserialization of elasticsearch request type

- horreum-web/src/domain/alerting/ChangeTable.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2091
> Properly parse changes timestamp

- horreum-web/src/domain/alerting/ChangeTable.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2105
Fixes https://github.com/Hyperfoil/Horreum/issues/2091
> [0.15] Properly parse changes timestamp

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
If a user has a composite role (like `dev-uploader`) it will get the base roles from keycloak (in this case `dev-team` and `uploader`) as well.
At the moment the API key only provides the composite roles. It should give the same set of composite and base roles.
> Add base roles to API keys

- infra-legacy/example-configuration.sh
Fixes https://github.com/Hyperfoil/Horreum/issues/2126
> Update example-configuration.sh horreum user

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2133
although nothing is displayed in the UI, it may help to debug in situations where the query is valid but no runs are created.
> [0.15] Improve response sstatus code when query return no results

- horreum-web/src/domain/user/UserSettings.tsx
> Set URL anchor on API Keys tab

- .github/workflows/branch.yml
- .github/workflows/release.yml
Aligns the release workflow version to the branch it is ran from.
The workflow is disabled for the `master` branch.
> Update release.yml action

- docs/site/content/en/docs/Concepts/users/index.md
- docs/site/content/en/docs/Deployment/bare-metal.md
- docs/site/content/en/docs/Reference/APIFilterQueryReference.md
- docs/site/content/en/docs/Tasks/import-export/index.md
- docs/site/content/en/docs/Tasks/manage-reports/index.md
- docs/site/content/en/docs/Tasks/upload-run/index.md
- docs/site/content/en/docs/Tutorials/create-test-run/index.md
- docs/site/content/en/docs/Tutorials/query-collector/index.md
- docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2176
> [0.16] Cleanup references to Bearer tokens and OIDC authentication for API usage

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> Fix error message in CollectorApiDatastore

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2197
> [0.16] Fix error message in CollectorApiDatastore

- horreum-web/src/domain/runs/RunData.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2215
> Fix updateSchema call from UI

- horreum-web/src/domain/runs/RunData.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2216
Fixes https://github.com/Hyperfoil/Horreum/issues/2215
> [0.16] Fix updateSchema call from UI

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
the issue is caused by running the `checkBootstrapAccount` methood with the `@WithRoles` annotation
> Fix issue where bootstrap account is created when there are already administrators

- README.md
Reference to DEVELOPMENT.md and RELEASE.md in the README.md file
> Reference to DEVELOPMENT.md and RELEASE.md in the README.md file

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
- horreum-web/src/domain/tests/AllTests.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2281
Fixes https://github.com/Hyperfoil/Horreum/issues/2282
> Fix updateSettings and tests listing 

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExperimentComparison.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/TestExport.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/domain/schemas/SchemaList.tsx
- horreum-web/src/domain/tests/AllTests.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
- horreum-web/src/domain/tests/Experiments.tsx
- infra-legacy/example-data/quarkus_sb_test.json
Depends on https://github.com/Hyperfoil/Horreum/pull/2298
**Test Import**
**Schema Import**
> Split add update test import

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-web/src/domain/schemas/SchemaList.tsx
- horreum-web/src/domain/tests/AllTests.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1198
> Add schemas filtering by name

- horreum-web/src/components/TestSelect.tsx
- horreum-web/src/domain/reports/TableReportConfigPage.tsx
- horreum-web/src/domain/reports/TableReportPage.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2306
> Fix navigation bar for reports

- horreum-web/src/domain/alerting/RecalculateModal.tsx
> Fix typo in form label

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/pom.xml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Action.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Dataset.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ProtectedTimeType.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Run.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
- horreum-integration-tests/src/test/resources/application.properties
- horreum-web/src/domain/reports/TableReportConfigPage.tsx
- horreum-web/src/domain/runs/RunData.tsx
- horreum-web/src/domain/runs/RunImportModal.tsx
- horreum-web/src/domain/user/ApiKeys.tsx
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesPostgresConfig.java
- infra/horreum-infra-common/pom.xml
- pom.xml
Quarkus is updated to the latest version. Had conflicts with bouncycastle 1.80 so only upgraded to 1.79.
json-validator and smallrye-open-api-maven also updated to the latest version.
Did not upgrade keycloak as it introduced some regressions and I do not know how important it is.
KeycloakUserServiceTest.teamTest still fails for me most of the time so not sure if the upgrade caused any regressions for that test. If someone else can verify that would be great.
> Upgrade Quarkus and Smallrye openapi plugin

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-web/src/domain/admin/Datastores.tsx
- horreum-web/src/domain/tests/TestSettings.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2329
> Path signature '/api/config/datastore/{}' MUST be unique

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/ActionService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/api.tsx
- horreum-web/src/domain/actions/ActionList.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2343
> Separate global and test action endpoints

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/converter/ActionEventConverter.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ActionDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ActionMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionEvent.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2347
> Create custom action events enum

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/UserService.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2363
Fixes https://github.com/Hyperfoil/Horreum/issues/2362
> [0.18] Removed @Blocking from UserService

- horreum-integration-tests/pom.xml
- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2385
Fix release process that was not working.
Tested locally and it worked
> [0.18] Fix central portal repository config

- .github/workflows/release.yml
Looks like we were missing the `release` profile when performing the release in the CI
> Enable release profile during release in the ci

- .github/workflows/release.yml
- pom.xml
> Enable gpg artifact signing during release

- .github/workflows/release.yml
- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2389
> [0.18] Enable gpg artifact signing during release

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/DatasetService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
> Additional API improvements

- horreum-web/src/domain/runs/DatasetComparison.tsx
> Add "Export to CSV" button in DatasetComparison

- horreum-web/src/domain/alerting/PanelChart.tsx
> Fix change detection tooltip

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-web/src/About.tsx
This will help us identifying the proper commit related to a tag or more importantly to a SNAPSHOT version (e.g., in staging)
> Include the application commit in the version info

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/NotificationPluginTest.java
fixes #2295 and adds a test case
> fix API key expiration notification

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
Use the fingerprint hash directly in the `VarAndFingerprint` obj
> Use fingerprint hash for validTo concurrent obj

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/hibernate/JsonBinaryType.java
Fixes deprecation warning reported since Hibernate 7:
```
Overrides method that is deprecated and marked for removal in 'org.hibernate.usertype.UserType' 
```
> Adapt custom JsonBinaryType to hibernate 7

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- infra-legacy/example-data/quarkus_quickstart_test_empty.json
- infra-legacy/example-data/quarkus_sb_compare_ds.json
- infra-legacy/example-data/quarkus_sb_run1.json
- infra-legacy/example-data/quarkus_sb_run2.json
- infra-legacy/example-data/quarkus_sb_run3.json
- infra-legacy/example-data/quarkus_sb_run4.json
If approved should be merged after the larger refactor @lampajr did.
> Added test with actual run data to trigger recalculations and removed dataset from Fingerprint

- pom.xml
update keycloak to match the keycloak-client version used on quarkus
> Update keycloak to 26.0.6
