- horreum-client/src/test/java/io/hyperfoil/tools/HorreumTestBase.java
fixes #96
This implementation is not very elegant, but operations to check file permissions on a ZipFile throw an UnsupportedOperationException, so there is no easy way to discover the original file permissions.
The other option is to remove the file copy code in `prepareDockerCompose()` and use the maven-dependency-plugin to unpack dependencies in the project importing the testsuite. This would retain the correct permissions, but require each project to declare the maven-dependency-plugin in it's pom.xml
> Fix script permissions when client testsuite is used as a dependancy

- pom.xml
This PR changes the configuration for the life-cycle mapping. To explicitly define the run goal as the default.
> Solve issue with Eclipse build triggering repeatedly.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
- horreum-backend/src/main/resources/templates/change_notification_email.html
When tests grouped by similar benchmark name and splitted by dataset then it is hard to distinguish the benchmark out of the notification.
> Add group name to notification

- horreum-backend/pom.xml
This temporarily fixes #187
In order to upgrade to reactive rest client, we need to ensure we do not break `horreum-client` module
> Revert use reactive RESTEasy client

- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
This PR disables a test that passes in local env, but fails in CI.
In order for the CI to be valuable for testing other changes, the test has been disabled until the root cause of the issue can be resolved.
> Disable flaky test. Need to resolve transaction issue

- webapp/src/domain/reports/TableReportView.tsx
Scales gets as a baseline options.
Then each row of the table recalculates due to the baseline
> Add baseline change comparison to the report tables

- infra/start.sh
#In `start.sh` changed the version value from `0.6` to `0.7,` which is the more recent one. Issue: #348
> version changed to more recent release in start.sh

- horreum-model/src/main/java/io/hyperfoil/tools/horreum/api/RunService.java
Adding this openapi annotation for the response of `RunService.addRunFromData`, the generated yaml file with the api definition is more correct, allowing to produce better client for the run service.
> added openapi annotation for the response of RunService.addRunFromData

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
fixes #591 
This PR adds a DDL statement to remove the existing foreign key constraint named `fk_dataset_run_id`. Also adds the Liquibase configuration that will create a new constraint. A constraint from datapoint table to dataset.
> Added fk constraint from datapoint to dataset

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
- webapp/src/domain/reports/TableReportView.tsx
in the situation there is no dataset associated with a Component. Added testcase for this issue.
fixes issue #567 
This change will add a null reference check to filter the Report references.  These exist in the situation when a report Component has an associated Label but for whatever reason there is no dataset. It can happen.
> Added change to handle null value. 

- horreum-backend/pom.xml
- horreum-integration-tests/pom.xml
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesKeycloakConfig.java
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesPostgresConfig.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
- pom.xml
Dev services now;
- work correctly with podman and cgroups2
- extracts the dev service images up to `application.properties` to allow easier syncing of image versions
- removes hard-coded dev service images
- introduces `horreum.dev-services.keycloak.container-port` config to allow for writing tests against a known keycloak port
> Fix dev services on podman, plus tesing enhancements

- horreum-backend/src/main/resources/db/changeLog.xml
Allow backport of #854 into 0.9.x branch by re-ordering of DB changesets.  There has not been a release of 0.10 yet, so unless someone is running a version of Horreum built from main branch, this should be "safe"
> Allow backport of #854 to 0.9.x branch

- horreum-backend/src/main/resources/application.properties
let's try latest LTS node version in horreum I have downgrade npm version because on the top of the website they say this version include npm 10.1.0 check this-https://nodejs.org/en/download
> Node: Latest LTS Version: 20.9.0

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ReportComponentMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
Backport of https://github.com/Hyperfoil/Horreum/pull/918
> Do not filter report config if report is not peristed: Fixes #877

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
This reverts commit db778fe8c7f04c575e5c717f82bb9d54c52f2fc0.
Backport of: https://github.com/Hyperfoil/Horreum/pull/980
> Revert "Add permissions check on PG dump directory and helpful error message."

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
This reverts commit 3d5bc4d9a6e923a41158f08b19dc8a7fa8b2e174.
> Revert "Compare fingerprints by hash"

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
- horreum-web/index.html
- horreum-web/package-lock.json
- horreum-web/package.json
- horreum-web/src/index.tsx
- horreum-web/src/setupProxy.js
- horreum-web/tsconfig.json
- horreum-web/vite-env.d.ts
- horreum-web/vite.config.ts
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1076
CRA (create-react-app) is no longer maintained. Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects
closes: #995
> [0.11.x] Migration CRA to VITE

- horreum-web/src/domain/runs/TestDatasets.tsx
When number of filters exceeds window width.
Currently the filters disappear off the screen.
fixes #960 
Now the window will render a horizontal scroll bar.
> Configure overflow setting to render a better UI. 

- horreum-web/src/domain/runs/TestDatasets.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1170
When number of filters exceeds window width.
Currently the filters disappear off the screen.
fixes #960 
Now the window will render a horizontal scroll bar.
> [0.11.x] Configure overflow setting to render a better UI. 

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/HorreumAuthorizationFilter.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
- infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1118
`ConfigService` will return `horreum.keycloak.url=""` when `quarkus.oidc.auth-server-url` is not defined.
> [0.11.x] Fix dev service to start postgres only and allow horreum to start without oidc.auth-server-url

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-web/src/domain/runs/Run.tsx
Fixed calling the wrong apis function when updating Run access.
fixes #406 
fixes #1145
> Detect when RLS has been a cause for error.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-web/src/domain/runs/Run.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1147
Fixed calling the wrong apis function when updating Run access.
fixes #406 
fixes #1145
> [0.11.x] Detect when RLS has been a cause for error.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1226
- allow unauthenticated users to query public datastores
- return public datastores for users who not belong to test owning team
- added tests
- added success/error messages to UI
- fixed UI dropdown and updating issues
Fixes #1204
> [0.11.x] Change permissions on retreiving Datastores: Fixes #1204

- horreum-web/package-lock.json
- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1224
> [0.11.x] Fix conflicting npm dependencies and bump typescript 4 to 5

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-web/src/Login.tsx
- horreum-web/src/api.tsx
- horreum-web/src/keycloak.ts
Reverts Hyperfoil/Horreum#1183
I am reverting this PR as all current PR's are currently failing on CI.  
I opened https://github.com/Hyperfoil/Horreum/issues/1246 to track fixing the failing build, but as I can no longer test open PR in CI I need to revert and we can re-apply when the original PR has been rebased ontop of current master and fixed
Thanks
> Revert "Add endpoint to fetch the roles of an authenticated user: Fixes #1187"

- horreum-web/src/App.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/domain/admin/Admin.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1276
Fixes #1275
> [0.11.x] Display datastore config to managers in Admin tab: Fixes #1275

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/BaseDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/Datastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/PostgresDatastore.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-web/package-lock.json
- horreum-web/src/App.tsx
- horreum-web/src/domain/admin/Datastores.tsx
- horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1299
Fixes #1295
> [0.11.x] Implement Basic Authentication for Elasticsearch datastore: Fixes #1295

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
Preserves DTO object ordering to UI.
fixes #929  issue
[x] - Add testcase to check Runs ordering in ASC or DESC mode.
[x] - Add testcase to check Datasets ordering in ASC or default DESC mode.
[x] - Fix the default ordering to Descending
[x] - Fixs the loss of ordering when creating a list of DTO objects
> Changed default ordering to Decending and preserve ordering of DTOs. 

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UIService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UIServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/api.tsx
- horreum-web/src/domain/tests/Views.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1315
Closes #1312
The `UIService` `updateView` now returns the updated `View` not just the `id` because the updated view can contain new `ViewComponents` and the client needs to know the new `ids` for those `ViewComponents`
An alternative could be to fetch all the `Views` after updating any `View` but that would re-fetch data that did not change. It might simplify the client code but would add unnecessary IO to the backend. I think there are better improvements to be made to the client code with where and how views are cached in the javascript but that is for a later PR.
> [0.11.x] closes #1312 with updated UIService api

- horreum-web/src/domain/runs/TestDatasets.tsx
Test Datasets would not correctly show any custom View Components on the Default view until the user selected `Default` from the `ViewSelector`.
closes #529
> fix default view not rendering additional components on load

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/IndexedLabelValueMap.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/LabelValueMap.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/DatasetService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
openapi.yaml generation from annotations is a dark art I don't yet fully undestand. I would hope the annotations offer the same expression as we can achieve with concrete types or by had writing the yaml but I cannot find the solution.
Instead I changed the data type to a subclass of `HashMap<>` so that openapi will generate a custom schema and reference it for docs and clients.
Closes #1325
> fix 1325 with concrete return types

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Closes #1323
related to #1092
this adds the `/api/run/{id}/labelValues` endpoint to mirror `/api/test/{id}/labelValues` and it uses a similar format
```
[ { datasetId, values: { [labelName]: labelValue},...]
```
TODO:
> fix #1323 by adding /api/run/{id}/labelValues

- horreum-web/src/domain/runs/TestDatasets.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1318
Test Datasets would not correctly show any custom View Components on the Default view until the user selected `Default` from the `ViewSelector`.
closes #529
> [0.11.x] fix default view not rendering additional components on load : Fixes #529

- horreum-web/src/domain/runs/RunList.tsx
- horreum-web/src/domain/tests/General.tsx
This will break any existing `test.compareUrl` in the production db but I think it is the best option for #1328
Horreum would no longer let users define how `runId` is added to their comparison url. Horreum would add `id=runId` for each selected run (e.g. `?id=101&id=102` if multiple are selected)
Closes #1328
> fixes 1328 using compareUrl as a url not javacript function

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/ChangeDetection.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Action.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/alerting/ChangeDetectionDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ActionDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/actions/ActionComponentForm.tsx
- horreum-web/src/domain/tests/ActionsUI.tsx
- horreum-web/src/domain/tests/VariableForm.tsx
This gets us to only 2 python client generation warnings, both about `text/plain` body content in a `post`
```
#> openapi-python-client generate --path /tmp/openapi.yaml
Generating horreum-rest-api-client
Warning(s) encountered while generating. Client was generated, but some pieces may be missing
WARNING parsing POST /api/run/{id}/description within run. Endpoint will not be generated.
Unsupported content type text/plain
WARNING parsing POST /api/run/{id}/schema within run. Endpoint will not be generated.
Unsupported content type text/plain
If you believe this was a mistake or this tool is missing a feature you need, please open an issue at https://github.com/openapi-generators/openapi-python-client/issues/new/choose
```
The issue is already opened with `openapi-python-client` …
> python-client: add Schema + impl to ObjectNode api returns

- horreum-web/src/domain/runs/TestDatasets.tsx
I know I already fixed this once but apparently the "default" test can be `default` or `Default` or whatever else we want so now Horreum will just display whatever is shown by default in the view selector until we find the next issue with it
closes #1332
> fixes #1332 by using first loaded view as default

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ProtectedTimeType.java
Should generate a corrected openapi.yaml. We should also look at testing the generated openapi.yaml with all endpoints?
closes: #1336
> fix 1336 with corrected start and stop annotations

- horreum-web/src/domain/runs/TestDatasets.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1333
I know I already fixed this once but apparently the "default" test can be `default` or `Default` or whatever else we want so now Horreum will just display whatever is shown by default in the view selector until we find the next issue with it
closes #1332
> [0.11.x] fixes #1332 by using first loaded view as default

- horreum-api/pom.xml
The generated  code is located in horreum-api/target/generated.
The generation itself does not add much to the build time, still not sure if we should run it on every build in the future, but to avoid breaking the clients (again) I think we should have it enabled for now.
> Added python and go code generation as part of the api build, fixes #1278

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/ChangeDetection.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/changeDetection/ChangeDetectionModelType.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/changeDetection/FixThresholdConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/changeDetection/FixedThresholdDetectionConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/changeDetection/RelativeDifferenceDetectionConfig.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/BaseChangeDetectionConfig.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection/ChangeDetectionModel.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection/ChangeDetectionModelResolver.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection/FixedThresholdModel.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection/RelativeDifferenceChangeDetectionModel.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-web/package-lock.json
Fixes #1380
This PR adds Descriminators to the openAPI spec, which allows the Typescript generator to generate individual mappings for the different Change Detection Configuration types. 
This is a "partial" fix, in that it restores functionality but still relies on hard-coded values. 
Eventually this needs to be fully dynamic, based in the ChangeDetection implementation type, but that requies a much bigger refactor
> Add Change Detection Config Discriminators: Fixes #1380

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
Adds service that performs migration of `roles` from keycloak to horreum DB.
Depends on the new security model #1304  
Fixes #1261
> Security migration - Fixes #1261

- .github/workflows/backport.yml
Disable the squashing during automated backporting, this way all commits belonging to the original PR will be part of the backporting PR.
Moreover I suggest to fix the github action version to `v4.5.1` as the `main` branch might be unstable.
> Backporting: disable squash and fix version

- docs/site/content/en/docs/Tutorials/grafana/index.md
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
This improves the openapi docs for the `labelValues` endpoints on `/api/test` and `/api/run` as well as giving more details on `/labelValues` filtering in the grafana tutorial.
> update labelValues openapi examples and grafana tutorial

- pom.xml
This plugin was added to get the eclipse editor working, it's no longer needed.
> removed lifecycle-mapping plugin, fixes lsp used for vscode/nvim

- .gitignore
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-web/src/About.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1408
Provide additional `privacy` statement in the `About` popup:
The link/URL is configurable at installation/build level using property `horreum.privacy`.
> Add configurable privacy statement link

- .gitignore
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-web/src/About.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1437
Fixes https://github.com/Hyperfoil/Horreum/issues/1408
Provide additional `privacy` statement in the `About` popup:
The link/URL is configurable at installation/build level using property `horreum.privacy`.
> [0.12.x] Add configurable privacy statement link

- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
Followup of https://github.com/Hyperfoil/Horreum/pull/1437
Disable by default the privacy statement link so that by default it is not shown in the webpage.
> Disable the privacy statement by default

- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1440
Followup of https://github.com/Hyperfoil/Horreum/pull/1437
Disable by default the privacy statement link so that by default it is not shown in the webpage.
> [0.12.x] Disable the privacy statement by default

- .github/workflows/backport.yml
- docs/RELEASE.md
1. Made `no-squash` option configurable, by default is set to `true` (i.e., using label `backport`) but if you want to force `no-squash: false` for any reason you can simply add label `backport-squash` rather than `backport` one.
2. Added `concurrency` so that if multiple jobs are triggered targeting the same PR only one will be kept alive
> Backport: disable no-squash with backport-squash label

- horreum-web/vite.config.ts
The auto open browser tab opens to the nodejs port but that hostname + port combo does not work with the sign on so we end up working with the quarkus port. This disables the auto open tab. We can re-visit whenever the sign on works with requests from the node port.
> disable auto browser tab in dev mode

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RolesAugmentor.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
- horreum-backend/src/main/resources/application.properties
Fixes #1445 
Fixes #1419
This PR makes the UserService "backend" (keycloak/database) runtime configurable; 
- The same property selects the backend, but is resolved at runtime not build time. We only have to build one image 
- defaults back to keycloak behaviour - the upgrade from keycloak to database will be an admin choice
- there is an additional check for migration, that the database backend has been selected AND the tables are empty
- prevents a "split-mode" - Fixes #1419
Once migrated from keycloak -> database, everything continues to function with the roles resolved from the database
> Make UserService backend runtime configurable: Fixes #1445

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RolesAugmentor.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
- horreum-backend/src/main/resources/application.properties
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1450
Fixes #1445 
Fixes #1419
This PR makes the UserService "backend" (keycloak/database) runtime configurable; 
- The same property selects the backend, but is resolved at runtime not build time. We only have to build one image 
- defaults back to keycloak behaviour - the upgrade from keycloak to database will be an admin choice
- there is an additional check for migration, that the database backend has been selected AND the tables are empty
- prevents a "split-mode" - Fixes #1419
Once migrated from keycloak -> database, everything continues to function with the roles resolved from the database
> [0.12.x] Make UserService backend runtime configurable: Fixes #1445

- docs/site/content/en/docs/Concepts/core-concepts/index.md
- docs/site/content/en/docs/Tasks/configure-actions/index.md
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1464
Added details of webhook types and an event type.
fixes #1177 
[x] - Added links to existing Configure Actions page.
[X] - Added more terms on Core Concepts page.
[x] - Added events that can be created in Horreum
[x] - Types of Action
> [0.12.x] Added links on existing Configure Actions documentation page.

- .github/workflows/backport.yml
As part f the https://github.com/Hyperfoil/Horreum/issues/1423 resolution
Bump `backporting` to the latest version that runs on `node20`, therefore removing the following warning:
```bash
[run](https://github.com/Hyperfoil/Horreum/actions/runs/8214138182/job/22466298403)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: wow-actions/welcome@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Bump backporting to version 4.5.2

- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/ElasticsearchTestProfile.java
Create a new test profile, currently only for `DatasourceTest`.
> Remove general use of Elasticsearch dev service

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
Fix the `e.printStackTrace` from Util.toInstant and add unit tests for `toInstant` that cover known timestamp conversions.
closes #1486
> fix #1486 and add Util unit tests

- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/ElasticsearchTestProfile.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1498
Create a new test profile, currently only for `DatasourceTest`.
> [0.12.x] Remove general use of Elasticsearch dev service

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1497
Fix the `e.printStackTrace` from Util.toInstant and add unit tests for `toInstant` that cover known timestamp conversions.
closes #1486
> [0.12.x] fix #1486 and add Util unit tests

- horreum-web/package-lock.json
- horreum-web/package.json
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1515
Bumps [@patternfly/patternfly](https://github.com/patternfly/patternfly) from 5.1.0 to 5.2.1.
Bumps [@patternfly/react-core](https://github.com/patternfly/patternfly-react) from 5.1.1 to 5.2.3.
Bumps [@patternfly/react-table](https://github.com/patternfly/react-table) from 5.1.1 to 5.2.4.
> [0.12.x] Bump @patternfly from 5.1.x to 5.2.x in /horreum-web

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
Check if the string value of the time passed to Util.toInstant is blank before trying to convert the value. This will prevent logging the error message when toInstant should not attempt a conversion. Also changed from warn to debug when logging the failed conversion because failed user conversions are expected rather than something that requires a warning.
closes #1514
> fix 1514 with empty string check

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1536
Check if the string value of the time passed to Util.toInstant is blank before trying to convert the value. This will prevent logging the error message when toInstant should not attempt a conversion. Also changed from warn to debug when logging the failed conversion because failed user conversions are expected rather than something that requires a warning.
closes #1514
> [0.12.x] fix 1514 with empty string check

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatabaseUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/DatabaseRolesTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/PostgresResource.java
(Also includes some changes in the service and back-ends to make them behave as same as possible) 
Add abstract class with test cases and two concrete implementations, one for each back-end. Each implementation has it's own custom `QuarkusTestProfile`.
The test injects the service and call it's methods directly. This is simpler and allows greater control and therefore better coverage.
> UserService tests

- docs/site/content/en/docs/Tutorials/grafana/index.md
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/domain/runs/TestDatasets.tsx
`labelValues` can contain a large number of entries or a large amount of data depending on how a team uses labels. Including all labels for every request can create large json responses and impact the performance of Horreum and the perceived peformance of services that consume the endpoint. 
This adds the `include` and `exclude` query parameters to the `labelValues` endpoint for both runs and tests so that users have more control over what data they fetch from Horreum.
Closes #1530
> add include and exclude to test and run service labelValues endpoint

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
In order to be able move out of a "roles" based to a "user" based row level security in the future, it's wise to reserve username starting with `horreum.`.
> Reserve usernames starting with "horreum."

- .github/workflows/backport.yml
Upgrade the `git-backporting` action to include the fix for https://github.com/kiegroup/git-backporting/issues/114 as multiple commits were applied in the wrong order which could have led to conflicts if the commits were updating the same file.
Upgrade to version `v4.7.1`.
> Upgrade backport to v4.7.1

- .github/workflows/notify-clients.yaml
- docs/RELEASE.md
Fixes https://github.com/Hyperfoil/Horreum/issues/1550
Fixes https://github.com/Hyperfoil/Horreum/issues/1545
Automate the clients notification every time there is a change in the `openapi` spec.
The notification is implemented using the `peter-evans/repository-dispatch@v3`.
> Automate openapi changes notification to Horreum clients

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/bus/AsyncEventChannels.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-web/src/Banner.tsx
- horreum-web/src/domain/schemas/Schema.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1579
Changes:
> MPL-68: make run_schemas updates asynchronous

- horreum-api/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
- horreum-backend/src/main/resources/templates/change_notification_email.html
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/NotificationPluginTest.java
- horreum-web/package-lock.json
- horreum-web/src/App.tsx
- horreum-web/src/alerts.tsx
- horreum-web/src/auth.tsx
- horreum-web/src/components/FoldersAccordian.tsx
- horreum-web/src/components/FoldersDropdown.tsx
- horreum-web/src/components/FragmentTabs.tsx
- horreum-web/src/components/SaveChangesModal.tsx
- horreum-web/src/components/TeamSelect.tsx
- horreum-web/src/domain/admin/Admin.tsx
- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/reports/Reports.tsx
- horreum-web/src/domain/reports/TableReportConfigPage.tsx
- horreum-web/src/domain/reports/TableReportPage.tsx
- horreum-web/src/domain/runs/DatasetData.tsx
- horreum-web/src/domain/runs/Run.tsx
- horreum-web/src/domain/runs/RunList.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/schemas/SchemaList.tsx
- horreum-web/src/domain/tests/AllTests.tsx
- horreum-web/src/domain/tests/Test.tsx
- horreum-web/src/domain/tests/TestSettings.tsx
Horreum UI refactoring.
In summary, here the most important changes:
> Horreum UI refactoring

- docs/site/content/en/docs/Concepts/core-concepts/index.md
- docs/site/content/en/docs/Reference/APIFilterQueryReference.md
- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/SqlService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
fixes issue #796 
[x] - Add annotation information on API operations
[X] - Add documentation about Queries
> Add examples to API that support a query.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/bus/MessageBusChannels.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-web/src/Banner.tsx
- horreum-web/src/domain/schemas/Schema.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1581
Fixes https://github.com/Hyperfoil/Horreum/issues/1579
Changes:
> [0.12.x] MPL-68: make run_schemas updates asynchronous

- .github/workflows/check.yml
- horreum-web/.prettierrc
- horreum-web/package-lock.json
- horreum-web/package.json
fixes #1552 
[x] - Change workflow to write the file in the correct format
> Reformat package-lock.json and package.json to single spacing.

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
the user management should rely only on the configuration of the `keycloak-admin` extension. that is independent of the OICD configuration.
> Fix SecurityMigration realm

- .github/workflows/main.yml
Proposing to add a check for uncommitted changes during PR checks, this is going to ensure that all those autogenerated files are properly committed (doing this especially for the openapi spec)
> CI: check for uncommitted changes

- .github/workflows/backport.yml
As per [discussion](https://github.com/Hyperfoil/Horreum/discussions/1601), this is my proposal for the backporting cherry-pick strategy in order to be more confident on the backported changes.
> Change backporting strategy

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Roles.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-web/src/domain/schemas/SchemaList.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1589
> MPL-75: Establish schemas team selector

- .github/workflows/main.yml
Backport https://github.com/Hyperfoil/Horreum/pull/1611
Proposing to add a check for uncommitted changes during PR checks, this is going to ensure that all those autogenerated files are properly committed (doing this especially for the openapi spec)
> [0.12.x] CI: check for uncommitted changes

- horreum-web/src/domain/alerting/Changes.tsx
- horreum-web/src/domain/tests/ChangeDetectionForm.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1639
Proposing to remove the "Go to changes" redirection from "Change detection" tab as it is no more needed given that with the latest UI refactoring both "Changes" and "Change detection" are under the `Test` page.
> Remove go to changes button

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/JpaIdentityProviderRolesExtension.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BasicAuthTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/DatabaseRolesTestProfile.java
at the moment authenticating with `security-jpa` is not possible due to row level security blocking access to the user info.
intercepting the DB call in`JpaIdentityProvider` allows setting the role and proceed with authentication against the username / password stored in the DB. 
Fixes: #1701
> Intercept JPAIdentityProvider to set the required roles

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
Fixes: #1723 
In the flamegraphs below, calls to `Util.setupContext()` are highlighted
Before;
After ;
> Only initialize graal JS context when required. Fixes #1723

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumKeycloakTestResourceLifecycleManager.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
- horreum-integration-tests/src/main/resources/application.properties
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
This PR adds a mechanism that generates an account that can be used to bootstrap Horreum. That account should be removed once there are other accounts in the system.
Its another step towards removing dependency on keycloak and also custom dev-services. 
fixes https://github.com/Hyperfoil/Horreum/issues/1719
> Create initial account when there are no accounts in the system

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumKeycloakTestResourceLifecycleManager.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
- horreum-integration-tests/src/main/resources/application.properties
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1708
This PR adds a mechanism that generates an account that can be used to bootstrap Horreum. That account should be removed once there are other accounts in the system.
Its another step towards removing dependency on keycloak and also custom dev-services. 
fixes https://github.com/Hyperfoil/Horreum/issues/1719
> [0.14] Create initial account when there are no accounts in the system

- horreum-web/src/components/LabelFilter/FilterDropDown.tsx
- horreum-web/src/components/LabelFilter/LabelFilter.tsx
- horreum-web/src/components/LabelFilter/LabelFilterOption.tsx
- horreum-web/src/components/ToolbarLabelFilter.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
This PR changes the filter dropdown to use the Patternfly `attribute-search` pattern
Fixes:  #1346
> Change dataset filters to Patternfly Attribute Filter pattern: Fixes: #1346

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/SchemaDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ChangesServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SqlServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
fixes #1766 
it's no longer necessary to escape `::` (native typecast operator) and it's not desirable
reference [HHH-17759](https://hibernate.atlassian.net/browse/HHH-17759) and [https://github.com/hibernate/hibernate-orm/pull/8007](https://github.com/hibernate/hibernate-orm/pull/8007)
> Fix native typecast in queries

- horreum-web/src/domain/runs/DatasetComparison.tsx
Fixes #1879
Dynamically resolve the custom views for Compare Datasets
> Dynamically resolve custom views in Compare Datasets: Fixes #1879

- horreum-web/src/domain/runs/DatasetComparison.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1880
Fixes #1879
Dynamically resolve the custom views for Compare Datasets
> [0.14] Dynamically resolve custom views in Compare Datasets: Fixes #1879

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
> Replace Test.get calls when not really required

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1894
> [0.14] Replace Test.get calls when not really required

- horreum-client/pom.xml
- horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
This will allow the client to be used in the horreum backend classpath in the future.
> Improve horreum client

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
In situations where the OIDC server is not manged by Horreum (an external SSO provider is used) make the distinction between `horreum.keycloak.realm` (the realm that is sent to the front end and used for authentication) and `quarkus.keycloak.admin-client.realm` (a managed realm used for migration in those scenarios).
This change aligns the realm definition with the usages of `@Inject Keycloak`.
> Fix horreum realm for oidc deployments

- horreum-client/pom.xml
- horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1901
This will allow the client to be used in the horreum backend classpath in the future.
> [0.14] Improve horreum client

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1900
In situations where the OIDC server is not manged by Horreum (an external SSO provider is used) make the distinction between `horreum.keycloak.realm` (the realm that is sent to the front end and used for authentication) and `quarkus.keycloak.admin-client.realm` (a managed realm used for migration in those scenarios).
This change aligns the realm definition with the usages of `@Inject Keycloak`.
> [0.14] Fix horreum realm for oidc deployments

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
At the moment, everytime a user open the administrator tab a warning saying that it is not able to list machine accounts for a specific team (the one selected by default, i.e., the first one) alongside the exception which says that the role is NOT FOUND is printed in the logs.
```bash
2024-09-09 10:50:46,107 e4b3085409dd quarkus-run.jar[7] WARN  [io.hyp.too.hor.svc.use.KeycloakUserBackend] (executor-thread-23917) Unable to list machine accounts for team <MY_TEAM>: jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:242)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:216)
at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntity …
```
> Return empty list if machine role is not present

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
There have been reports of IO treads blocked while sending out email notifications. 
Since horreum uses the async email extension, the other possible cause is qute templating.
> Use async qute templating for email notifications

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/ArtemisMQResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
> Make key names consistent with prior resources.

- horreum-api/pom.xml
- horreum-client/pom.xml
> Fix target version to JDK11 for api and client

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
Fixes the sequential handling of multi-upload datastore types. 
Fixup of https://github.com/Hyperfoil/Horreum/pull/1859
> Fix sequential handling of multi upload type with less than 10 items

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2036
Fixes the sequential handling of multi-upload datastore types. 
Fixup of https://github.com/Hyperfoil/Horreum/pull/1859
> [0.15] Fix sequential handling of multi upload type with less than 10 items

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserApiKey.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/UserApiKeyMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/Notification.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/ApiKeyAuthenticationMechanism.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/ApiKeyIdentityProvider.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RolesAugmentor.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TimeService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/main/resources/templates/api_key_expiration_email.html
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
- horreum-client/src/main/java/io/hyperfoil/tools/CustomResteasyJackson2Provider.java
- horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
- horreum-client/src/main/java/io/hyperfoil/tools/auth/HorreumApiKeyAuthentication.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/user/ApiKeys.tsx
- horreum-web/src/domain/user/UserSettings.tsx
> Auth Token feature

- horreum-web/src/domain/tests/TestSettings.tsx
> repopulate datasources when team owner changes for test. Fixes: #2049

- horreum-web/src/domain/tests/TestSettings.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2050
Fixes: #2049
> [0.15] repopulate datasources when team owner changes for test. Fixes: #2049

- horreum-backend/pom.xml
- horreum-integration-tests/pom.xml
- horreum-web/package-lock.json
- horreum-web/package.json
- infra/horreum-dev-services/runtime/pom.xml
- infra/horreum-infra-common/pom.xml
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
- pom.xml
Keycloak version was incompatible with services running SSO
Fixes: #2061
> Downgrade Keycloak to 23.0.7

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/LabelValuesService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/LabelValuesServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
I am proposing to move part of the `/labelValues` logic from jdbc to Java, especially the json aggregation.
This seems coming with a huge improvement, here some results I obtained:
**Before**
**After**
**Before**
**After**
> Move label values json aggregation into Java

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/LabelValuesService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
- horreum-backend/src/main/resources/application.properties
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/LabelValuesServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1977
I am proposing to move part of the `/labelValues` logic from jdbc to Java, especially the json aggregation.
This seems coming with a huge improvement, here some results I obtained:
**Before**
**After**
**Before**
**After**
> [0.15] Move label values json aggregation into Java

- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
> Removed the unused profile and resource.

- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
In preparation for the removal of machine accounts.
> Remove use of machine account in integration tests

- .github/workflows/main.yml
- horreum-backend/src/main/docker/Dockerfile.jvm.base
Fixes https://github.com/Hyperfoil/Horreum/issues/2079
> Fix python and hunter version

- .github/workflows/main.yml
- horreum-backend/src/main/docker/Dockerfile.jvm.base
Followup of https://github.com/Hyperfoil/Horreum/pull/2080.
Pin the python version that we embed in the Horreum container, this comes with some good improvements:
- Reproducibility of the build
- Clearly state the python version being used
- Ensure CI uses and test the same version we use in the container
> Pin python version 3.9 into the horreum-base

- .github/workflows/main.yml
- horreum-backend/src/main/docker/Dockerfile.jvm.base
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2085
Followup of https://github.com/Hyperfoil/Horreum/pull/2080.
Pin the python version that we embed in the Horreum container, this comes with some good improvements:
- Reproducibility of the build
- Clearly state the python version being used
- Ensure CI uses and test the same version we use in the container
> [0.15] Pin python version 3.9 into the horreum-base

- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
This was initially meant to address https://github.com/Hyperfoil/Horreum/issues/2078 but it looks like the before/after filtering is actually working as expected.
Therefore, at the moment, I am proposing to simply add some more testing that will improve the labelValues coverage.
> Add before/after labelValues filtering test

- horreum-web/src/components/LabelFilter/FilterDropDown.tsx
- horreum-web/src/components/LabelFilter/LabelFilter.tsx
- horreum-web/src/components/LabelFilter/LabelFilterOption.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2071
Set the `Default` view id as soon as the views are fetched.
Additionally I fixed a couple of errors that were thrown in the logs, i.e., setting a unique key on list elements.
> Set default view by default

- horreum-web/src/components/LabelFilter/FilterDropDown.tsx
- horreum-web/src/components/LabelFilter/LabelFilter.tsx
- horreum-web/src/components/LabelFilter/LabelFilterOption.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2087
Fixes https://github.com/Hyperfoil/Horreum/issues/2071
Set the `Default` view id as soon as the views are fetched.
Additionally I fixed a couple of errors that were thrown in the logs, i.e., setting a unique key on list elements.
> [0.15] Set default view by default

- horreum-client/src/main/java/io/hyperfoil/tools/horreum/api/client/RunService.java
[This change](https://github.com/Hyperfoil/Horreum/pull/641/files#diff-c3cbefab12e12b2c5bfaa7dde40f95e053e03ca209c6cca20ab56357942000b5) was not carried over to the `RunService` representation on the java client, causing a mismatch between client and server.
Calls to the `add()` method will always result in a `404 Not Found` response.
> Fix RunService in java client

- horreum-client/src/main/java/io/hyperfoil/tools/horreum/api/client/RunService.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2117
[This change](https://github.com/Hyperfoil/Horreum/pull/641/files#diff-c3cbefab12e12b2c5bfaa7dde40f95e053e03ca209c6cca20ab56357942000b5) was not carried over to the `RunService` representation on the java client, causing a mismatch between client and server.
Calls to the `add()` method will always result in a `404 Not Found` response.
> [0.15] Fix RunService in java client

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/resources/application.properties
This strategy keeps accepting new messages even if one failed, therefore without closing the connections at first failure.
Fixes https://github.com/Hyperfoil/Horreum/issues/2103
The default messaging fail strategy is `fail` which stops the application from receiving messages at first failure, as stated here https://quarkus.io/guides/amqp-reference#failure-management
> Set AMQP strategy to modified-failed

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-web/src/api.tsx
- horreum-web/src/domain/tests/RecalculateDatasetsModal.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/1975
> Do not use recalc lock for run-recalc

- horreum-web/src/domain/schemas/Labels.tsx
the definition of `deleteLabel` is 
``` javascript
deleteLabel(schemaId: number, labelId: number)
```
> fix delete labels from the ui

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-web/src/api.tsx
- horreum-web/src/domain/tests/RecalculateDatasetsModal.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2084
Fixes https://github.com/Hyperfoil/Horreum/issues/1975
> [0.15] Do not use recalc lock for run-recalc

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
- horreum-backend/src/main/resources/templates/tags/dataset_link.md
- horreum-web/src/domain/alerting/ChangeTable.tsx
- horreum-web/src/domain/alerting/RecalculateModal.tsx
- horreum-web/src/domain/reports/TableReportView.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/ExperimentModal.tsx
- horreum-web/src/domain/runs/TestDatasets.tsx
- horreum-web/src/domain/schemas/TestLabelModal.tsx
- horreum-web/src/domain/schemas/TryJsonPathModal.tsx
Currently in the UI the datasets ordering is starting from 1, whereas the ordering in the backend start from 0.
This could create some confusion, when both conventions are reported in the UI, e.g., https://github.com/Hyperfoil/Horreum/issues/2093. 
Moreover, all the urls that contain some datasets identifiers use the backend convention (starting from 0).
My proposal is to unify the convention and make use of the 0ed one, this would also simplify its management in the UI.
> UI datasets ordering starting from 0

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-web/src/domain/runs/RunImportModal.tsx
attempt to fix #2098. I don't have a test for this right now.
this change causes the generated `horreum-web/src/generated/apis/RunApi.ts` file to change from:
```javascript
return await response.value();
```
to 
``` javascript
switch (response.raw.status) {
case 200:
return await response.value();
case 202:
return null;
default:
return await response.value();
}
```
this should prevent the `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` error, reported in the issue, that prevents the dialog from closing.
also added a `catch` call to be double safe.
>  Specify the 202 Accepted response in RunService API

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
Follows the same change that have been done for run recal 👉🏻  https://github.com/Hyperfoil/Horreum/pull/2084
> Remove hardcoded test recalc timeout

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-web/src/domain/runs/RunImportModal.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2124
attempt to fix #2098. I don't have a test for this right now.
this change causes the generated `horreum-web/src/generated/apis/RunApi.ts` file to change from:
```javascript
return await response.value();
```
to 
``` javascript
switch (response.raw.status) {
case 200:
return await response.value();
case 202:
return null;
default:
return await response.value();
}
```
this should prevent the `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` error, reported in the issue, that prevents the dialog from closing.
also added a `catch` call to be double safe.
> [0.15]  Specify the 202 Accepted response in RunService API

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2122
Follows the same change that have been done for run recal 👉🏻  https://github.com/Hyperfoil/Horreum/pull/2084
> [0.15] Remove hardcoded test recalc timeout

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
although nothing is displayed in the UI, it may help to debug in situations where the query is valid but no runs are created.
> Improve response sstatus code when query return no results

- horreum-backend/src/main/resources/db/changeLog.xml
> [COMP-LABELS] Cleanup and fix composable-labels model changeset

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
Early improvement that would consider `{}` as empty filter, this way the query is a LOT easier and faster.
This does not solve the performance issue we currently have when the filter is set, as it would require a refactoring that might be not necessarily as we are trying to get rid of the datasets entirely.
> Datasets listing should treat {} as empty filter

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2162
Early improvement that would consider `{}` as empty filter, this way the query is a LOT easier and faster.
This does not solve the performance issue we currently have when the filter is set, as it would require a refactoring that might be not necessarily as we are trying to get rid of the datasets entirely.
> [0.15] Datasets listing should treat {} as empty filter

- docs/site/content/en/docs/Concepts/users/index.md
- docs/site/content/en/docs/Deployment/bare-metal.md
- docs/site/content/en/docs/Reference/APIFilterQueryReference.md
- docs/site/content/en/docs/Tasks/import-export/index.md
- docs/site/content/en/docs/Tasks/manage-reports/index.md
- docs/site/content/en/docs/Tasks/upload-run/index.md
- docs/site/content/en/docs/Tutorials/create-test-run/index.md
- docs/site/content/en/docs/Tutorials/query-collector/index.md
- docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
> Cleanup references to Bearer tokens and OIDC authentication for API usage

- horreum-client/src/main/java/io/hyperfoil/tools/auth/HorreumApiKeyAuthentication.java
Fixes the horreum-client generation, in particular:
```
Error:  /home/runner/work/Horreum/Horreum/horreum-client/src/main/java/io/hyperfoil/tools/auth/HorreumApiKeyAuthentication.java:10: error: reference not found
Error:      /** sync with {@link io.hyperfoil.tools.horreum.server.ApiKeyAuthenticationMechanism} */
Error:                           ^
```
Remove the link in the javadoc comment
> Fix horreum-client javadoc generation

- horreum-client/src/main/java/io/hyperfoil/tools/auth/HorreumApiKeyAuthentication.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2179
Fixes the horreum-client generation, in particular:
```
Error:  /home/runner/work/Horreum/Horreum/horreum-client/src/main/java/io/hyperfoil/tools/auth/HorreumApiKeyAuthentication.java:10: error: reference not found
Error:      /** sync with {@link io.hyperfoil.tools.horreum.server.ApiKeyAuthenticationMechanism} */
Error:                           ^
```
Remove the link in the javadoc comment
> [0.16] Fix horreum-client javadoc generation

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/ArtemisMQResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
1. change `ARTEMIS_USER / ARTEMIS_PASSWORD` to `AMQ_USER / AMQ_PASSWORD` that are the variable names defined in https://github.com/artemiscloud/activemq-artemis-broker-image/blob/main/image.yaml 
2. add wait strategy to both AMQ and Horreum containers
3. misc code improvements
> Fix Horreum and AMQ test containers

- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/ArtemisMQResource.java
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2181
1. change `ARTEMIS_USER / ARTEMIS_PASSWORD` to `AMQ_USER / AMQ_PASSWORD` that are the variable names defined in https://github.com/artemiscloud/activemq-artemis-broker-image/blob/main/image.yaml 
2. add wait strategy to both AMQ and Horreum containers
3. misc code improvements
> [0.16] Fix Horreum and AMQ test containers

- docs/site/hugo.toml
Enable the offline search and simultaneously disable the google custom search engine that was pointing to the docsy dev site
Fixes https://github.com/Hyperfoil/Horreum/issues/2188
This is the result:
> docs: enable offline search

- docs/site/hugo.toml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2189
Enable the offline search and simultaneously disable the google custom search engine that was pointing to the docsy dev site
Fixes https://github.com/Hyperfoil/Horreum/issues/2188
This is the result:
> [0.16] docs: enable offline search

- horreum-web/src/domain/runs/RunImportModal.tsx
Removes redundant argument that used to be internal/test `token`.  The
parameter was removed in https://github.com/Hyperfoil/Horreum/pull/2100
This essentially fixes the "Import Data"/"Import New Run" form which currently always results in using the `schemaUrn` as a description, and `undefined` as the payload.
> Fix `runApi.addRunFromData()` invocation

- horreum-web/src/domain/runs/RunImportModal.tsx
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2194
Removes redundant argument that used to be internal/test `token`.  The
parameter was removed in https://github.com/Hyperfoil/Horreum/pull/2100
This essentially fixes the "Import Data"/"Import New Run" form which currently always results in using the `schemaUrn` as a description, and `undefined` as the payload.
> [0.16] Fix `runApi.addRunFromData()` invocation

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2196
Trashing a run that was already trashed should have no effects and it should not throw an exception
Fixes https://github.com/Hyperfoil/Horreum/issues/2160
Trying to trash a run that has been already trashed will result in a no-operation
> [0.16] Trash run even if it is already trashed

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/Version.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceWithAsyncProcessingTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/AMQPInMemoryResource.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/ElasticsearchTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/InMemoryAMQTestProfile.java
- horreum-client/src/main/java/io/hyperfoil/tools/horreum/api/client/RunService.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
Refactor the process such that runs and related datasets get created/persisted synchronously whereas the datasets processing (label values calculation and so on) is deferred to the async process by making use if the dataset-even queue
Fixes https://github.com/Hyperfoil/Horreum/issues/1976
This change proposes to slightly update how the Run upload is managed, moving from a completely sync process to a hybrid one.
The process can be summarized as follow:
1. Persist the Run and any related dataset in the same transaction (if everything goes fine obv).
2. Once run and datasets are flushed, send dataset events to the `dataset-event` queue to process label values (and change point detection and so on) asynchronously.
TODOs/Open points:
- ~[ ] Adapt the UI~ nothing to do here
> Refactor the Run upload process

- docs/site/content/en/docs/Reference/APIFilterQueryReference.md
- docs/site/content/en/docs/Tasks/import-export/index.md
- docs/site/content/en/docs/Tasks/manage-reports/index.md
- docs/site/content/en/docs/Tasks/upload-run/index.md
- docs/site/content/en/docs/Tutorials/create-test-run/index.md
- docs/site/content/en/docs/Tutorials/query-collector/index.md
- docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
This is in response to issues user experienced using the examples from the docs in ansible automation. Placing the `$API_KEY` variable reference outside of the single quote parameter definition for `curl -H` in ansible did not properly set the request header. It does work if the variable reference is located inside a double quote (`"`). Changing the documented examples will work in bash and avoid providing examples that conflict with ansible's command line processing.
> change API_KEY examples to avoid ansible issues

- docs/site/content/en/docs/Reference/APIFilterQueryReference.md
- docs/site/content/en/docs/Tasks/import-export/index.md
- docs/site/content/en/docs/Tasks/manage-reports/index.md
- docs/site/content/en/docs/Tasks/upload-run/index.md
- docs/site/content/en/docs/Tutorials/create-test-run/index.md
- docs/site/content/en/docs/Tutorials/query-collector/index.md
- docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2210
This is in response to issues user experienced using the examples from the docs in ansible automation. Placing the `$API_KEY` variable reference outside of the single quote parameter definition for `curl -H` in ansible did not properly set the request header. It does work if the variable reference is located inside a double quote (`"`). Changing the documented examples will work in bash and avoid providing examples that conflict with ansible's command line processing.
> [0.16] change API_KEY examples to avoid ansible issues

- docs/site/content/en/docs/Reference/horreum-clients.md
Fixes https://github.com/Hyperfoil/Horreum/issues/2208
> docs: fix clients examples to use api key

- horreum-web/src/About.tsx
- horreum-web/src/components/LogModal.css
- horreum-web/src/components/LogModal.tsx
- horreum-web/src/domain/alerting/RecalculateModal.tsx
- horreum-web/src/domain/runs/DatasetComparison.tsx
- horreum-web/src/domain/runs/LabelValuesModal.tsx
- horreum-web/src/domain/runs/ValidationErrorTable.tsx
- horreum-web/src/domain/schemas/TestLabelModal.tsx
- horreum-web/src/domain/schemas/TryJsonPathModal.tsx
fixes #1369 
I replaced the `Table` with a `DescriptionList` where appropriate
> Remove use of deprecated table

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
Fixes https://github.com/Hyperfoil/Horreum/issues/2201
> Fix calc_dataset_view join with label values

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2202
Fixes https://github.com/Hyperfoil/Horreum/issues/2201
> [0.16] Fix calc_dataset_view join with label values

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
- horreum-web/src/domain/admin/Administrators.tsx
- horreum-web/src/domain/admin/Teams.tsx
- horreum-web/src/domain/user/ManagedTeams.tsx
- horreum-web/src/domain/user/NewUserModal.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2174
> Make user pwd not required with oidc

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UIServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
Followup pull request of https://github.com/Hyperfoil/Horreum/pull/2202
This is not meant to be backported.
Fixes https://github.com/Hyperfoil/Horreum/issues/2220
Move the `dataset_view` update logic from db to Horreum java logic.
As part of this refactoring the following entities have been removed:
- Tables
-  view_recalc_queue and:
- Triggers
- dsv_after_delete
- dsv_after_update
- recalc_dataset_view
- dsv_after_insert
- Functions:
- dsv_after_vc_delete_func
- dsv_after_vc_update_func
- recalc_dataset_view
- dsv_after_lv_insert_func
Moreover the `calc_dataset_view(datasetId bigint, viewId bigint DEFAULT NULL)` signature has changed
such that it can be called in two different scenarios, i.e., by dataset or by dataset-view.
> Remove view recalc queue

- docs/DEVELOPMENT.md
- docs/RELEASE.md
Closes https://github.com/Hyperfoil/Horreum/issues/2165
Update the `RELEASE.md` file with the latest instructions. Due to that previous content was entirely removed. It will be easy to review if you open the rendered version in a new tab.
> Update the RELEASE.md file with the latest instructions

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2242
After deeper investigations it turned out the bug was introduced with https://github.com/Hyperfoil/Horreum/pull/2172 that basically removed the `@Transactional` annotation around the `persistRun` method, which is the one invoked by the `upload-run` async emitter.
My guess is that, given that there is not explicit transaction wrapping that method the `roleManager.setRoles(String.join(",", runUpload.roles));` instructions is not visible from the rest of the logic (where the run is persisted) resulting in missing roles at the db level.
Changes:
> Make persistRun transactional

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2243
Fixes https://github.com/Hyperfoil/Horreum/issues/2242
After deeper investigations it turned out the bug was introduced with https://github.com/Hyperfoil/Horreum/pull/2172 that basically removed the `@Transactional` annotation around the `persistRun` method, which is the one invoked by the `upload-run` async emitter.
My guess is that, given that there is not explicit transaction wrapping that method the `roleManager.setRoles(String.join(",", runUpload.roles));` instructions is not visible from the rest of the logic (where the run is persisted) resulting in missing roles at the db level.
Changes:
> [0.17] Make persistRun transactional

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/TestExport.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2249
Clears existing id's if we're importing a new test. Also check for null on the id field that caused the import issue.
> Clear id's importing a new test, check for null

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2268
Looking into https://horreum.hyperfoil.io/openapi/#tag/Schema/operation/addOrUpdateLabel API doc says `id` ("Unique ID for Label") is required. This should be only required when you are updating label, not adding new one. It confused me.
Just a tiny docs change.
> [0.17] docs: Add a note that label id is only required when updating label

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2248
Changes affected the Test import feature as follows:
> Fix test import when datastore is provided

- horreum-backend/pom.xml
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/LabelValuesService.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/LabelValuesServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceWithAsyncProcessingTest.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2266
With https://github.com/Hyperfoil/Horreum/pull/1977 we changed how the labelValues implementation was done, the main change was that we moved the run/datasset aggregation from db logic to Java for performance reasons.
Unfortunately this change introduced the regression described in https://github.com/Hyperfoil/Horreum/issues/2266.
With this change I am proposing to move the `limit` logic to Java as well, given that it would be quite not possible to do that at db level given that the aggregation is not there anymore.
> Fix label values limits

- horreum-web/src/domain/runs/Run.tsx
On a Run page (e.g. `/run/53069#run`) one header was missing.
Adding the table header.
> fix: Add missing owner header

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
Fixes https://github.com/Hyperfoil/Horreum/issues/2228
Fixes https://github.com/Hyperfoil/Horreum/issues/2231
Moved the logic to update `run_schemas` and `dataset_schemas` into Horreum logic and as a consequence I removed the following entities:
Triggers:
- ds_after_insert
- rs_after_run_untrash
- rs_after_run_update
- before_schema_update
Functions:
- ds_after_dataset_insert_func
- rs_after_run_update
- before_schema_update_func
I kept the procedure `update_run_schemas` in the db as it is always called by the Horreum directly.
Additionally with commit https://github.com/Hyperfoil/Horreum/pull/2230/commits/714223f199ed0cac77e5fec2c65faa21d9d7e392 I removed the remaining triggers on `Run` table:
- after_run_update_non_data, moved logic into Horreum
- delete_run_validations, we are not even …
> Removing remaining database triggers

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/resources/db/changeLog.xml
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2230
Fixes https://github.com/Hyperfoil/Horreum/issues/2228
Fixes https://github.com/Hyperfoil/Horreum/issues/2231
Moved the logic to update `run_schemas` and `dataset_schemas` into Horreum logic and as a consequence I removed the following entities:
Triggers:
- ds_after_insert
- rs_after_run_untrash
- rs_after_run_update
- before_schema_update
Functions:
- ds_after_dataset_insert_func
- rs_after_run_update
- before_schema_update_func
I kept the procedure `update_run_schemas` in the db as it is always called by the Horreum directly.
Additionally with commit https://github.com/Hyperfoil/Horreum/pull/2230/commits/714223f199ed0cac77e5fec2c65faa21d9d7e392 I removed the remaining triggers on `Run` table:
- after_run_update_non_data, moved …
> [0.17] Removing remaining database triggers

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
Partial backport of https://github.com/Hyperfoil/Horreum/pull/2283
Fixes https://github.com/Hyperfoil/Horreum/issues/2281
> [0.17] Fix notification settings creation

- docs/site/content/en/openapi/openapi.yaml
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Label.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Schema.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Transformer.java
- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceWithAsyncProcessingTest.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
- horreum-web/src/domain/schemas/Labels.tsx
- horreum-web/src/domain/schemas/Schema.tsx
- horreum-web/src/domain/schemas/Transformers.tsx
**Schema**
**Labels**
**Transformers**
> Split add and update schema apis

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/AlertingService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/alerting/ChangeDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
- horreum-web/src/domain/alerting/PanelChart.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2096
> Visually distinguish confirmed changes with green dots

- horreum-web/src/domain/alerting/PanelChart.tsx
Fixes https://github.com/Hyperfoil/Horreum/issues/2140
> Show datapoints till the first 2 non-zero decimals

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
The method `Run.addRun` was properly configured to return an array of ints but the implementation was returning it as String.
This is causing some issues on the auto generate Python client as it is expecting an array but getting a single element instead - The same problem does not happen in Golang as for some reason it is able to parse it anyway.
This method is not used anywhere in the source code, nor in the Jenkins plugin.
> Fix the return type of Run.add to be array of ints

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceNoRestTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
Backport https://github.com/Hyperfoil/Horreum/pull/2326
The method `Run.addRun` was properly configured to return an array of ints but the implementation was returning it as String.
This is causing some issues on the auto generate Python client as it is expecting an array but getting a single element instead - The same problem does not happen in Golang as for some reason it is able to parse it anyway.
This method is not used anywhere in the source code, nor in the Jenkins plugin.
> [0.17] Fix the return type of Run.add to be array of ints

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/converter/ActionEventConverter.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ActionDAO.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ActionMapper.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionEvent.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2348
Fixes https://github.com/Hyperfoil/Horreum/issues/2347
> [0.18] Create custom action events enum

- horreum-client/src/main/java/io/hyperfoil/tools/RunServiceExtension.java
- horreum-client/src/main/java/io/hyperfoil/tools/horreum/api/client/RunService.java
- horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
This aims to include all methods from originl RunService but the addRunFromData that has FileUpload as param
I noticed that the HorreumClient is overriding the `RunService` because of the `addRunFromData`, which is leaking some reactive objects (i.e., `FileUpload`). Thus, the RunService defined in the client is not up to date wrt to the latest changes and improvements.
I am proposing to update so that we include all methods in the client RunService (e.g., get Run label values was missing).
> Update the HorreumClient Run service

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
Fixes the following issue:
```bash
Details:
Error id f14c801d-fbbc-4252-9d2d-8b85c0d0a3d4-1, java.lang.IllegalArgumentException: id to load is required for loading
Decorate (Source code):
Exception in ActionServiceImpl.java:371
369          for (Action a : test.actions) {
370              ActionDAO action = ActionMapper.to(a);
→ 371              if (ActionDAO.findById(action.id) == null) {
372                  action.id = null;
373                  action.persist();
Stack:
java.lang.IllegalArgumentException: id to load is required for loading
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:77)
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:43)
at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:207)
at …
```
> Fix test import with actions

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
The current `ExperimentComparisonDeserializer` is wrong as it should convert String to ExperimentComparison but it is not: https://github.com/Hyperfoil/Horreum/blob/36985dc81fd95d826be608c42ffd302a9024b279/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java#L193-L198
While trying to fix it I did not find any valuable reason to keep ExperimentComparison as the key of the results given that they will be deserialized to string anyway and no-one else is using those results.
> Remove custom serializer for ExpComparison results

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2368
Fixes the following issue:
```bash
Details:
Error id f14c801d-fbbc-4252-9d2d-8b85c0d0a3d4-1, java.lang.IllegalArgumentException: id to load is required for loading
Decorate (Source code):
Exception in ActionServiceImpl.java:371
369          for (Action a : test.actions) {
370              ActionDAO action = ActionMapper.to(a);
→ 371              if (ActionDAO.findById(action.id) == null) {
372                  action.id = null;
373                  action.persist();
Stack:
java.lang.IllegalArgumentException: id to load is required for loading
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:77)
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:43)
at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(I …
```
> [0.18] Fix test import with actions

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2366
The current `ExperimentComparisonDeserializer` is wrong as it should convert String to ExperimentComparison but it is not: https://github.com/Hyperfoil/Horreum/blob/36985dc81fd95d826be608c42ffd302a9024b279/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java#L193-L198
While trying to fix it I did not find any valuable reason to keep ExperimentComparison as the key of the results given that they will be deserialized to string anyway and no-one else is using those results.
> [0.18] Remove custom serializer for ExpComparison results

- .github/workflows/release.yml
- docs/RELEASE.md
- horreum-backend/pom.xml
- pom.xml
Migrate from the end-of-life OSSRH sonatype service to the new Central Portal one
Migrating from OSSRH service to Central Portal one by following https://central.sonatype.org/publish/publish-portal-maven/#publishing guide.
> Migrate to Central Portal

- pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2383
```
Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.2:deploy (default-deploy) on project horreum: Failed to deploy artifacts: Could not find artifact io.hyperfoil.tools:horreum:pom:0.18.3 in central (https://central.sonatype.com/) -> [Help 1]
Error: [ERROR] 
Error: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: [ERROR] 
Error: [ERROR] For more information about the errors and possible solutions, please read the following articles:
Error: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
> [0.18] Fix central portal repository url

- horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Dataset.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/resources/application.properties
Alternative approach that fixes https://github.com/Hyperfoil/Horreum/issues/2391 as suggested in https://github.com/Hyperfoil/Horreum/pull/2392
> Process dataset-event with different priorities

- horreum-api/pom.xml
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2405
Fix Central Portal deployment validation issue:
```
pkg:maven/io.hyperfoil.tools/horreum-api@0.18.4
Project name is missing
```
> [0.18] Add artifact name for Horreum API

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/main/resources/application.properties
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2412
Increase the default buffer size for `dataset-event-out` to accomodate datasets recalc on schema label updates
> [0.18] Increase default buffer size for dataset-event-out

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
I am afraid that sending dataset event in different TX callbacks we are sending events completely asynchronously and when there is a huge amount of them we might risk to hit some race condition that could cause wrong credit calculation on amqp client:
```
2025-06-25 10:59:45,580 645a1466d4ef /usr/lib/jvm/java-17-openjdk-17.0.15.0.6-2.el9.x86_64/bin/java[7] ERROR [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16225: Failure reported for channel `dataset-event-out`, closing client: java.lang.IllegalArgumentException: Invalid request number, must be greater than 0
at io.smallrye.mutiny.helpers.Subscriptions.getInvalidRequestException(Subscriptions.java:24)
at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.request(MultiOperatorProcessor.java:117)
at …
```
> Emit all datasets recalc in one consumer

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
**Backport:** https://github.com/Hyperfoil/Horreum/pull/2425
I am afraid that sending dataset event in different TX callbacks we are sending events completely asynchronously and when there is a huge amount of them we might risk to hit some race condition that could cause wrong credit calculation on amqp client:
```
2025-06-25 10:59:45,580 645a1466d4ef /usr/lib/jvm/java-17-openjdk-17.0.15.0.6-2.el9.x86_64/bin/java[7] ERROR [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16225: Failure reported for channel `dataset-event-out`, closing client: java.lang.IllegalArgumentException: Invalid request number, must be greater than 0
at io.smallrye.mutiny.helpers.Subscriptions.getInvalidRequestException(Subscriptions.java:24)
at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.request( …
```
> [0.18] Emit all datasets recalc in one consumer

- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionEvent.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
- horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ActionServiceTest.java
- horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
- horreum-web/src/domain/actions/ActionComponentForm.tsx
- horreum-web/src/domain/actions/reducers.ts
https://issues.redhat.com/browse/MPL-960
**Problem**
At the moment users can get notified when a new Run is uploaded, but given the async nature of the run upload logic (which means that label values are calculated asynchronously after some time) they cannot rely on such event to retrieve label values data.
**Proposal**
Introduce a new event "new/dataset" that, if subscribed (through actions config), users can get notifed when a "dataset" is completely computed - this means that this should be triggered when label values for a specific datasets are finalized (or recalculated?)
**Acceptance criteria**
Introduce additional "new/dataset" event
Ensure configured actions gets called when all label values are computed for that dataset
> Add new Dataset Labels Computed event

- horreum-backend/src/main/resources/application.properties
- infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/HorreumResource.java
Based on the documentation at https://quarkus.io/guides/amqp-reference
```
The interval in second between two reconnection attempts
Type: int
```
We are using a too high value for `amqp-reconnect-interval`, as we are using `10000` that in seconds means `>15 mins`
> Reduce AMQP reconnect interval
